### ISSUE TITLE
Does this implement the CSS Syntax spec?

### ISSUE THREAD

**Issue by domenic** [postcss/postcss#1051]
PostCSS comes with a basic CSS parser. But, was it just made up, or does it implement   https://drafts.csswg.org/css-syntax/ ? 

We're trying to find a new, maintained, CSS parser for jsdom, and PostCSS is one of the front runners, but we were really hoping to find something that was aligned with the spec and browsers.

**Comment by ai** [comment]
I created parser looking in this spec :). Its railway diagrams help a lot.

1. PostCSS can parse every valid document. I didn’t know anything from this spec, that we can’t parse. We even added escape tokens support (but nobody uses it) and has special logic for `url()` token (this token is not regular function token).
2. But also PostCSS could parse something more than just valid CSS. PostCSS is not a linter. If it could parse something non-standard — it will do it. For example, PostCSS will parse nested rules and unknown at-rules. I think this behavior is better because we don’t need new parser release for every CSS spec changes (like Sass needed a special release to not fall on Grid properties).
3. Unfortunately, there are no tests for this spec. I tried to pass it but didn’t test everything. But every PostCSS commit [is tested](https://github.com/postcss/postcss-parser-tests) with real CSS from Twitter, Bootstrap, etc to be sure, that we can parse every new property.
4. PostCSS is used in Autoprefixer and webpack, so at least we can’t be sure, that it parse most of CSS in the world as expected.

**Comment by hzlmn** [comment]
Just as an addition i think it would be nice to decouple parser in separate package. What do you think @ai?

**Comment by TrySound** [comment]
@hzlmn I'm not sure such fragmenting will be useful for community. PostCSS is not so big. It's just parser, traverser (+tree utils) and stringifier.

**Comment by ai** [comment]
@hzlmn `postcss/postcss` is a decouple parser in separate package ;)

**Comment by domenic** [comment]
Awesome, @ai! Does it also follow the spec's error-handling behavior? Your comments about "valid document" and "more than just valid CSS" make me worried it handles invalid CSS in a way different from a browser, which would make it hard to use in jsdom :-/.

**Comment by ai** [comment]
@domenic the only differences (as I understand it)

1. PostCSS understand nested rules. You can add an extra check and throw an error if you don’t want to support them.
2. PostCSS parse unknown at-rules and do not ignore it (like by spec at-rule could contain any content, not rules and decls). But it is only theoretically differences. There is no CSS specs or future draft with a non-standard content of at-rules.
