### ISSUE TITLE
Pin jest to version 21

### ISSUE THREAD

**Issue by JLHwung** [postcss/postcss#1099]
The recent test failure is due to the fact that Jest 22 drops node.js 4 support. It may be cumbersome to let Jest 22 works with node.js 4 without redistributing properly babelified jest, not to mention Jest 23 or later. So I suggest we pin the jest to version 21 until postcss drops node.js 4 support, too.

**Comment by ai** [comment]
Ha :). Pin old version is the too lazy way :).

I [convinced](https://github.com/facebook/jest/issues/5122) Jest team to add unofficial Node.js 4 support and send PR to [fix Node.js problems](https://github.com/facebook/jest/pull/5142).

Jest remove Node.js 4 support just because of JSDom. But we don’t use JSDom, so it is not a problem for us. Yarn `package.engine` check I already [disabled](https://github.com/postcss/postcss/blob/master/.travis.yml#L9) by `YARN_IGNORE_ENGINES`.

PostCSS will drop Node.js 4 support only when 4.x will end its LTS time (August 2018). Node.js Foundation promised to the community that Node.js 4 will be supported for all this period.

**Comment by simonsmith** [comment]
Looks like Node 4 is due to end its LTS at the end of this month - https://github.com/nodejs/Release

**Comment by ai** [comment]
@simonsmith yeap. I will release PostCSS 7 without Node.js 4 in this month.
