### ISSUE TITLE
PostCSS: ExtractTextPlugin run twice

### ISSUE THREAD

**Issue by ArielGueta** [postcss/postcss#1107]
I am trying to create a new postcss plugin. The problem is that when I am using the ExtractTextPlugin, the code is run twice, so if, for example, I'm appending new rule, it will append this twice.

I was looking for a solution and people are suggested to add `allChunks: true`, but it does not work.

```
css.walkRules(function (rule) {

    rule.walkDecls(function (decl, i) {

       // this is run twice with ExtractTextPlugin

    });

});
```

```
  "devDependencies": {
    "clean-css": "^4.1.9",
    "css-loader": "^0.28.9",
    "extract-text-webpack-plugin": "^3.0.2",
    "postcss": "^6.0.16",
    "postcss-loader": "^2.0.10",
    "style-loader": "^0.19.1",
    "webpack": "^3.10.0"
  }
```

**Comment by ai** [comment]
Show your webpack config.

**Comment by ArielGueta** [comment]
```
const ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = {
  entry  : './main.js',
  output : {
    filename: './dist/[name].js'
  },
  module : {
    rules: [

      {
        test   : /\.theme.css$/,
        exclude: /node_modules/,
        use    : ExtractTextPlugin.extract({
          allChunks: true,
          fallback : "style-loader",
          use      : [
            "css-loader",
            {
              loader : 'postcss-loader',
              options: {
                ident  : 'postcss',
                plugins: ( loader ) => [
                  require('./postcss-themes')
                ]
              }
            }
          ]
        })
      }
    ]
  },
  plugins: [
    new ExtractTextPlugin("./dist/main.css"),
  ],
};
```

**Comment by ArielGueta** [comment]
Found the solution:
Remove `fallback: "style-loader"` solved this.

**Comment by michael-ciniawsky** [comment]
Well this is 💯 unrelated to `postcss` and likely a problem with ETWP. ETWP extracts all modules from the `module.rule` with an `ExtractTextPlugin.extract()` and needs to rebuild each extracted module to remove it's dependencies from the Dependency Graph (e.g imports). The sorting logic there is very complicated, due to `.extract()` (loses the logic) and e.g `allChunks` is likely extracting some CSS twice if the module containing the CSS is referenced in more then one chunk. Which is 'correct'  but undesired...
