### ISSUE TITLE
PostCSS vs LESS.

### ISSUE THREAD

**Issue by ghost** [postcss/postcss#111]
So I've question: Does PostCSS faster then LESS parser && compiler? If yeap, how much does it faster?

**Comment by yairEO** [comment]
Can someone explain to me this - nowhere I understood the most important information, an that is if `postcss` can replace `SASS` or `LESS` and just compile the code as-is. I thought `postcss` is to replace those buy giving backward-compatibility support so current code won't need to be re-written (among it's other benefits)

**Comment by MoOx** [comment]
postcss is not a replacement for Sass nor Less. It's an alternative way to enhance your stylesheets written in plain CSS ("syntaxically" speaking). It provides a parser and an api to add your own custom behavior. You might want to use [some plugins](https://github.com/postcss/postcss#plugins) or directly tools like [cssnext](https://cssnext.github.io/) build on top of it.

**Comment by yairEO** [comment]
@MoOx - what?? but we already have that for a long time. using gulp or grunt modules to modify your CSS, things like `Autoprefixed` and `clean-css` and `combine-media-queries`, everyone already use them in build systems. Why then do I need `postCSS`? I could just use any module I wish and plug it into my gulp pipeline to modify the CSS.

**Comment by MoOx** [comment]
autoprefixer is a tool build on top of postcss. clean-css & combine-media-queries use differents css parser.
By using postcss and compatibles plugins, you can speed up your build time by avoiding multiples parsing step by each tool. PostCSS parse very nicely all the CSS syntax (and more) and is really fast.
Most tools based on postcss can be used as a plugin directly (so for example you can use autoprefixer as a postcss plugin with some others like cssnano to minify).

**Comment by MoOx** [comment]
gulp and grunt doesn't modify your CSS, they are just piping tools for your. You can do with the same with good old unix pipe (it's a metaphor but half true ^^).

**Comment by yairEO** [comment]
I wasn't aware autoprefixer has any relation to `postCSS`... and I've been using Autoprefixer for as long as it was out. Anyway, currently I see no reason to use postCSS with my current setup. maybe in the future when plugin-base will have better options to chose from. current gulp plugins and setup can work just the same.

**Comment by ai** [comment]
@yairEO yeap, yor are right. Gulp is plugin-based too. But it is a plugin-based task runner. Not a plugin based CSS tool. As result every CSS tool must parse CSS again. SO we have a 3 problems:

1. It is slow, because parsing is a most difffucult part of CSS tool. Right now you parse CSS 3 times for each tool.
2. It is unsafe. Good CSS parser is a complicated thing. It should parses legacy styles with syntax mistakes. It should parse some future standards. If we will have only one parser we will be able to test it better.
3. It is very difficult to develop CSS tool because you need to create CSS parser.

PostCSS solves this three problems. PostCSS is a one of the best CSS parsers. And ech plugin just process parsed once CSS nodes tree by chain.

So if you like Gulp rather that Makefile, youu know why PostCSS better than different tools:

1. It is very fast.
2. It has many awesome tools, because it is easy to create PostCSS plugin. If you already uses Autoprefixer, please check out [cssnext](https://cssnext.github.io/). It is a “Babel.js for CSS”, it compile fuuture CSS4 to current CSS3.

**Comment by yairEO** [comment]
well I guess most developers just download and use a CSS parser they found online, rather then each would spend the (huge) amount of time developing their own (which is absurd). I agree that it is much wiser to parse it once and then run any transformations. It might be fast but slowness  is not something I "feel" right now on a quite big CSS file (400kb non-minified).

gulp is a very good system and I think everyone should use it, and it would make more sense to me if there was a gulp module for only parsing CSS and all gulp modules would use it's output, something like this:

    gulp.task('scss', function(){
        gulp.src('*.scss')
            .pipe(cssGlobbing({ extensions:'.scss' }))
            .pipe(sass({ errLogToConsole: true })) 
            .pipe(cssParser()) // this is a one-time parser and everything now works with that data
                .pipe(cmq()) // combine media queries 
                .pipe(autoprefixer())
                .pipe(...) // whatever css transformation 
            .pipe(cssParser(output:'css')) // signal the parser to output pure CSS string and not parsed one
            .pipe(gulp.dest('../assets/css')) // write it to disk
    });

postCSS chose to be independent, decoupled from everything else, and in that "black box" you can choose to run transformations. That can be a good approach, but for me weird, because gulp is amazing and already became a standard, so the above approach seems quite logical

**Comment by ai** [comment]
It is very difficult to ompare Gulp and PostCSS. Because Gulp is a tool to run PostCSS. Have you look at [gulp-postcss](https://github.com/postcss/gulp-postcss)? It uuses ver close syntax as yo suggested:

```js
gulp.task('css', function ( ) {
    return gulp.src('./src/*.css')
        .pipe(postcss([
            autoprefixer({ browsers: ['last 1 version'] }),
            mqpacker,
            cssnano
        ]))
        .pipe(gulp.dest('./dest'));
});
```

**Comment by yairEO** [comment]
The way I see it, postcss is like an encapsulated GULP system, but only for CSS-related things.
still I see no justification for sandboxing everything under the postCSS eco-system. you loose the power everything GULP worked hard to achieve and all the plugins it proves which I might want to use in the middle of some CSS transformation. it should have a been a standalone parser for GULP IMHO.

**Comment by ai** [comment]
Autoprefixer has many users outside Gulp ecosystem ;). For example, how we can run Gulp plugins in webIDE like CodePen (it has Autoprefixer).

**Comment by yairEO** [comment]
yeah I am aware, it's an NPM module after all, and in GULP, it would mean a port like `gulp-autoprifixer` or anything else gulp-ported. Just a bit limiting from development point of view that all CSS transformations are un-accessible to other gulp modules to works as a "middle-man" manipulations.

**Comment by tunnckoCore** [comment]
lol, so awful discussion.. :D 

@yairEO I think it was just enough to say "we need streaming parser" which, yea, would be great - parse to AST or some api, and then we can transform it with streams (not only gulp plugins). But yea, I can agree, postcss is encapsulated and this is logical, there's no other way.

I only want to mention that I hate and love gulp, and this prefixing simple streams with "gulp-" - god damn, it is just stream nothing more, there's no need to be prefixed with gulp.

**Comment by ai** [comment]
@tunnckoCore do you know many stream Gulp plugins? ;-) I think all CSS Gulp plugins work with a full file content, not with a stream. Because most of CSS tasks need to look around in other parts of CSS files.

So there is no difference between gulp-postcss with PostCSS plugins and Gulp plugins.

**Comment by tunnckoCore** [comment]
> there is no difference between gulp-postcss with PostCSS plugins and Gulp plugins.

i didn't say that there have diffs in this workflow.
