### ISSUE TITLE
Speed up tokenizer by returning Uint32Array 

### ISSUE THREAD

**Issue by ai** [postcss/postcss#1162]
Right now tokenizer returns `[token_name, content, start_line, start_column, end_line, end_column]`

I think we can improve tokenizer performance if:

1. It will  return `Uint32Array(token_code, start_line, start_column, end_line, end_column)`
2. It will use the same `Uint32Array` instance again and again to avoid starting GC

**Comment by vitkarpov** [comment]
I've been diving here a little bit and found out that now it's really hard to change parser because of it works with token as an array directly, there are `token[0]`, `token[1]` here and there and so on. 

Why don't we make a special object and raw array would be an internal implementation, do you think it could be worse for performance? If you haven't actually checked it, I'd like to make this kind of refactoring first.

PS.

Yesterday I did a simple thing, which I thought was simple at first:

- created map token_name → token_code, changed names to codes in original tokens and exported method `getTokenNameByCode`
- each place where was `token[0]` I changed to `getTokenNameByCode(token[0])` — seems this parts have to work the same

Integration tests passed but I got a lot of errors from jest, like a lot, really 🙈Obviously I made a couple of silly but tricky mistakes. Seems it's not okay that parse and tokenizer are tight together with a such interface, doesn't it?

**Comment by vitkarpov** [comment]
> What do you mean? Can you show some code?

Sure, right now we're trying to work directly with arrays or Uint32Arrays (https://github.com/postcss/postcss/pull/1163) and every time we need to check the idea what could work better the whole codebase needs to be changed (as here https://github.com/postcss/postcss/pull/1163/commits/e5721f069eb3f4ad502e0829efadc705b4713ba1).

I think that token should be an instance of `Token`, like:

```js
class Token() {
  constructor(token_name, content, start_line, start_column, end_line, end_column) {
    ...
  }
}
```

With some getters/setters/methods which don't depend on inner implementation, so it could be applied different ideas and changes would be in the same place (in `Token` object constructor).

Seems it should be much overhead to create some extra object wrapped `Uint32Array` or anything.

**Comment by ai** [comment]
This wrapper class could affect on performance ;)

**Comment by vitkarpov** [comment]
> If we will convert code to string, we will reduce performance again

Yep, the first thing I wanted to make was refactoring, and I struggled because of high coupling two components token and parser.

> This wrapper class could affect on performance ;)

Sure it could but would it be? Did you really check this as it's the same single object, just a wrapper? If you're don't mind of the idea I could make the refactoring and check the performance.

**Comment by vitkarpov** [comment]
Sure if you have already done this before I believe you ;)

**Comment by ai** [comment]
You can try to make this thing in your branch, find the best way to increase performance and then remove `Token` back :+1: 

Or you suggested to always use `Token`?

**Comment by vitkarpov** [comment]
In the ideal world - yes, it should be there to decouple components. But if
it makes thing worse then surely it can’t be added at all.
вс, 1 июля 2018 г. в 20:42, Andrey Sitnik <notifications@github.com>:
