### ISSUE TITLE
Provide some way to prevent comment stripping

### ISSUE THREAD

**Issue by lluisrojass** [postcss/postcss#1206]
Currently, this hard requirement is handicapping `post-css`'s compatibility with [styled-jsx](https://github.com/zeit/styled-jsx#css-preprocessing-via-plugins) in a somewhat major way. Styled-jsx's approach to dynamic styles is to replace javascript logic with placeholders like so:

```javascript
<style jsx>{ `
 .rule {
      ${ hasBorder ? `border: 1px solid green;` : `` }
` }</style>
```

would be represented by

```javascript 

.rule { 
     %%styled-jsx-placeholder-0%%
 }

```

until an appropriate time later on when the javascript logic can run and accurately determine the correct css to place here. Compatibility between `post-css` and dynamic-styles here would mean employing a solution that allows these placeholders to persist past their post-css transformations. Since these placeholders could denote an unknown quantity of css and could exist at anytime within a chunk of css, the only solution is to [comment these portions out and uncomment them after transformation](https://github.com/giuseppeg/styled-jsx-plugin-postcss/blob/master/index.js#L5), causing the incompatibility :( 

https://github.com/zeit/styled-jsx#css-preprocessing-via-plugins
> Plugins won't transform expressions (eg. dynamic styles).

A possible solution would be to prefix comments like so `/*postcss-allow .... */` or maybe provide an option to allow comments all together.

**Comment by ai** [comment]
**TLTR:** use comments `/*%%styled-jsx-placeholder-0%%*/` instead of non-standard CSS syntax.

Full version:

So, do you want some custom extensions for CS syntax to keep placeholders during PostCSS transformation?

Good idea. Unfortunately, it is not really good for the parser maintainability to keep non-standard language extensions. It will require tests and work from us and these extensions could make PostCSS parser indomitable with browser’s standard CSS parsers in some edge cases. This is why I can’t add `%%something%%` support to PostCSS core parser.

But, don’t worry. We are here to care about our users and of course, we will provide you ways to solve your problem. I see two ways to keep placeholder:

1. You can write custom PostCSS parser to parse `%%something%%`. Here is a doc about writing [custom parsers](https://github.com/postcss/postcss/blob/master/docs/syntax.md). To be honest, I do not think this is the best way since it will require a lot of work to write it and keep updated. Also, DX for `styled-jsx` users could not be the best.
2. Maybe you should use some standard CSS syntax for placeholders? For instance, you can use comments `/*%%styled-jsx-placeholder-0%%*/`. It will require less work. It will allow you to use any CSS tools (not just PostCSS based).

**Comment by lluisrojass** [comment]
I'm not sure I follow here. The plugin currently already does this, it turns `%%styled-jsx-placeholder-0%%` into `/*%%styled-jsx-placeholder-0%%*/`, and then runs the css through post-css:

see here: https://github.com/giuseppeg/styled-jsx-plugin-postcss/blob/master/index.js#L5

I was under the impression that [PostCSS cleans values from comments by design.](https://github.com/postcss/postcss/issues/845#issuecomment-232306259) and that was why these comments were getting stripped, but it looks like you're saying there is way to prevent comment stripping? 

if so, i would love to know how 😄

**Comment by lluisrojass** [comment]
Closing this issue, thank you for your answer @ai, i'm going to investigate further.

**Comment by ai** [comment]
> I was under the impression that PostCSS cleans values from comments by design. and that was why these comments were getting stripped, but it looks like you're saying there is way to prevent comment stripping?

PostCSS strip comments only inside selectors `.one /* comment */ .two { }` or inside declaration values `color: /* comment */ black`.

In `.rule { /*%%styled-jsx-placeholder-0%%*/ }` comment will will be kept (not stripped).
