### ISSUE TITLE
Add Node.source.offset

### ISSUE THREAD

**Issue by nex3** [postcss/postcss#1325]
PostCSS nodes have a `source` property that indicates where in the source file the node was parsed from. However, this property only has `line` and `column` values, which makes it hard to figure out the absolute byte position of the node in the file. It would be useful to include this in the `source` as well.

For bonus points, provide a method in `Input` to translate an offset to a line/column pair and vice versa.

**Comment by ai** [comment]
Sure. We can add it to PostCSS 8.0.

It will be breaking changes because we need to change tokenizer API. Let’s replace `line`, `column` to `offset`. In `Input` we can use getter/setter to keep old API. Maybe it putting `offset` instead of `line`, `column` into tokens will speed up parsing a little.

I can create a task on our [Cult of Martians](https://cultofmartians.com/) (at Evil Martians we help Russian-speaking junior developers with this portal by giving contact and step-by-step instructions). But if you want you can send PR.

**Comment by nex3** [comment]
Thanks! I'm looking forward to it.

> But if you want you can send PR.

Unfortunately, I probably won't have time.

**Comment by ai** [comment]
It will be even better to help a junior developer to get a good line in their resume. I publish [the task](https://cultofmartians.com/tasks/postcss-offset.html#task) and I hope it will be pushed to 8.0 `ose` branch in the next few weeks.

Note, that PostCSS 8.0 release could take a while. We will need time to rewrite Autoprefixer, postcss-scss, and postcss-safe-parser. I am right now focusing on bringing [CRDT to React](https://logux.io/), so I open [funding for PostCSS 8.0 release](https://opencollective.com/postcss/) to use my work time for the release.

I am happy to release it before 8.0, but tokenizer changes will break API since a lot of parsers re-use core tokenizer.

Do you know whom I can speak at Google about funding PostCSS? In return, we will put a logo and link to tweets and release notes (and release notes for a major update is always a good ads platform).

**Comment by nex3** [comment]
> Note, that PostCSS 8.0 release could take a while. We will need time to rewrite Autoprefixer, postcss-scss, and postcss-safe-parser. I am right now focusing on bringing [CRDT to React](https://logux.io/), so I open [funding for PostCSS 8.0 release](https://opencollective.com/postcss/) to use my work time for the release.

One benefit of *adding* `offset` without replacing the existing properties is that it's no longer a breaking change, and wouldn't require downstream updates.

> Do you know whom I can speak at Google about funding PostCSS? In return, we will put a logo and link to tweets and release notes (and release notes for a major update is always a good ads platform).

I'll ask around.

**Comment by ai** [comment]
> One benefit of adding offset without replacing the existing properties is that it's no longer a breaking change

Of course. We can’t change `Node#source.start.line` even in major 8.0 since we can’t ask all plugin authors to rewrite plugins. Or migration policy for popular public API does not change them in one release. In one release we introduce a warning and only in next we remove/change API.

Unfortunately, adding `Node#source.start.offset` will require to change tokenizer API. The tokenizer is not a popular public API, but many tools use existed tokenizer. For instance, `postcss-safe-parser` and some other plugins. If we will change tokenizer API it will brake tools, which use PostCSS tokenizer.

Technically, we add `offset` as extra param in token `[type, content, line, column, offset]`, but I still do not sure that it is safe and the last param is not used by somebody.

If you need this feature before the major release, I see these options:

1. Add slow way right now with converting line/column to offset and replace it to fast method with PostCSS 8.0 release.
2. You can tell me more about your project and I will try to find some hack.

**Comment by ai** [comment]
Closed because PR with `offset` was merged to the 8.0 branch
