### ISSUE TITLE
SyntaxError: Unclosed block

### ISSUE THREAD

**Issue by sharifzadesina** [postcss/postcss#1336]
Hello,
I am getting this error:

```
ERROR in ./resources/sass/app.scss (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/dist/cjs.js??ref--5-5!./resources/sass/app.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(259:4) Unclosed block

  257 | 
  258 |   .navbar-toggler-icon {
> 259 |     background-image: escape-svg($navbar-light-toggler-icon-bg);
      |    ^
  260 |   }
  261 | 
```

**Comment by ai** [comment]
Because `$navbar-light-toggler-icon-bg` was not replaced, seems like you send SCSS content to PostCSS.

Very likely you have an issue in webpack config. You must have `sass-loader` before `postcss-loader` because by default PostCSS can process only CSS content.

Sorry, I can’t help you with webpack config. You can try to ask the webpack team on their Slack.

I am closing this issue because it is an environmental problem (if it is not I can reopen the issue later).
