### ISSUE TITLE
Leading asterisk in propery name is not reflected in parsed `prop`

### ISSUE THREAD

**Issue by silverwind** [postcss/postcss#1426]
I noticed a odd behaviour in the parser where a leading `*` in a property name like `*color` is omitted in the `prop` property and it is parsed as `color` (and `*` being put in `raws.before`).

Is this intentional? I don't see this behaviour with any other characters and trailing `*` is parsed as expected. Apparently this syntax is related to [IE hacks](https://stackoverflow.com/questions/1690642/purpose-of-asterisk-before-a-css-property/1690683#1690683), also see [this](http://www.javascriptkit.com/dhtmltutors/csshacks3.shtml#unrecommended-asterisk_prefix).

```css
> require("postcss").parse("a{*color: red}").nodes[0].nodes[0].prop
'color'
> require("postcss").parse("a{color*: red}").nodes[0].nodes[0].prop
'color*'
> require("postcss").parse("a{!color: red}").nodes[0].nodes[0].prop
'!color'
> require("postcss").parse("a{?color: red}").nodes[0].nodes[0].prop
'?color'
```

**Comment by ai** [comment]
`*color` was an old hack for IE. It was very popular a few years ago, thins is why we have a special logic for this case.

We didn’t added other IE chaks, since they were rare.

Right now it is a part of API and we do not want to change it.

Do you have any specific problem and idea how to fix PostCSS?

**Comment by silverwind** [comment]
My specific problem is that I simply want to access a declaration's property. I currently employ this workaround to also catch the `*`:

````js
function getDeclarationProperty(decl) {
  if (decl.raws && decl.raws.before && decl.raws.before.trim()) {
    return `${decl.raws.before.trim()}${decl.prop}`;
  } else {
    return decl.prop;
  }
}
````

Would you think that's sufficient? I imagine `raws.before` is usually just whitespace only, right?

**Comment by ai** [comment]
`raws.before` is for any meanless symbols before the Node. In 99% cases, it is whitespaces, but it can be anything (for instance, PostCSS Safe Parser put any non-recognized symbols there).

Sorry, you will need to use `getProperty` since we can’t break API and your case is rare to add a method to `Declaration`.

**Comment by silverwind** [comment]
Fine with me. Maybe you want to consider this breaking change in the future because that kind of parsing is not really like a modern and standards-compliant browser would parse it.
