### ISSUE TITLE
Source-map: Extra source in sources array

### ISSUE THREAD

**Issue by am11** [postcss/postcss#144]
Consider [the situation](https://github.com/less/less.js/issues/2310), where LESS compiler generated a source-map with absolute paths, like this:

``` json
{
    "version": 3,
    "sources": [ "C:/Users/Adeel/Documents/Visual Studio 2013/Projects/Testing WE issues and features/Testing WE issues and features/Content/less/Site.less" ],
    "names": [ ],
    "mappings": "AAAA,GACI;EACI,YAAA;EACA,sBAAsB,eAAtB",
    "file": "C:\\Users\\Adeel\\Documents\\Visual Studio 2013\\Projects\\Testing WE issues and features\\Testing WE issues and features\\Content\\fooLESS\\Site.css"
}
```

If we run postCSS on this output, the map is changed to:

``` json
{
    "version": 3,
    "sources": [
        "C:/Users/Adeel/Documents/Visual Studio 2013/Projects/Testing WE issues and features/Testing WE issues and features/Content/less/Site.less",
        "Site.css"
    ],
    "names": [ ],
    "mappings": "AAAA;EAEQ,cAAA;EACA,uCAAA;ECAP",
    "file": "Site.css"
}
```

The extra `"Site.css"` in `sources[]` array is incorrect. Sources array should probably never have a `.css` file in scenarios, where CSS file was generated from superset languages: less, sass etc.

//cc @MohammadYounes

**Comment by telegraphinho** [comment]
Why isn't it going to be fixed? People are complaining about it all over the place, including gulp autoprefixer repos. There is currently no way to overcome it, other than to remove name of css file manually(or using gulp.replace) from the `.map` file, which isn't very nice. Clearly it isn't the intended behaviour...

**Comment by ai** [comment]
You are totally welcome to fix this issue. I am always in gitter chat and will help you for any questions.

I will no do it myself before 4.2 release, because I think (maybe I am wrong and will be happy if you fix me), that noone will see this issue, until it opens source map file. Chrome Dev Tools didn't show any issues.

I understand that is incorrect output, but I think (really, correct me please if I am wrong), that better docs and async API is much more important tasks ;-).

So this task should be done by community's developer, who really think, that it is important. Like you ;-).

**Comment by telegraphinho** [comment]
I rechecked now and you are right! My bad, sorry.

I checked chrome dev-tools earlier today and the link in styles tab had lead to style.css file which didn't exist. I guess it was a one-time glitch, as i now it always leads to existing .sass file as it should.

I'll try to look into this anyway, but i'm not familiar with the source code and don't consider myself skilled enough to fix it. But i'll try, although i do understand your sarcasm)
