### ISSUE TITLE
Plugins ecosytem, tasks runners

### ISSUE THREAD

**Issue by pascalduez** [postcss/postcss#149]
Following your [Twitter request](https://twitter.com/postcss/status/540857025274855424).

I would really like to be able to plug any PostCSS plugins into a Gulp workflow.
To Gulp or not, it's not really the point, it should also work with Grunt and co.

It works with some and not with others, or really hard to find out how.
So more consistency in plugins could be a huge plus. Also names `postcss-*` would make it much easier to spot them.

For instance, some time ago I tried to use the following workflow, with `gulp-postcss`:

```js
var gulp = require('gulp');
var plumber = require('gulp-plumber');
var rubySass = require('gulp-ruby-sass')
var postcss = require('gulp-postcss');

gulp.task('styles', function () {
  var browsers = ['last 2 version', '> 1%', 'ie 9'];
  var processors = [
    require('autoprefixer-core')({ browsers: browsers }),
    require('postcss-url')({ url: 'inline' }),
    // require('pixrem')() // Could not make it work.
  ];

  return gulp.src('path/**/*.scss')
    .pipe(plumber())
    .pipe(rubySass())
    .pipe(postcss(processors))
    .pipe(gulp.dest('assets/css'));
});
```

The issue here was with `pixrem` but I'm pretty sure (from what I've seen) some other plugs might be affected as well.

____

**EDIT**:  Don't forget to initialize a new instance of processors. Works fine with latest versions.
`require('pixrem')()` or `require('pixrem')(rootvalue, options)`

**Comment by davidtheclark** [comment]
I have a question about plugin practices: 

Some plugins are themselves functions that receive CSS as an argument, and can therefore be used like this:

```js
postcss().use(plugin)
```

While other plugins return the functions that receive CSS as an argument, and therefore must be called to function, like this:

```js
postcss().use(plugin())
```

So consumers have to know which way each plugin works.

The latest PostCSS documentation here https://github.com/postcss/postcss#processor seems to suggest that the first way is the way to go --- but doesn't have an example of the best way to pass options objects. I'm assuming that people went the second route because it is useful for passing options objects.

@ai What is the way that you think plugin authors should do this? 

(This came up when I was working on my own plugins and also here: https://github.com/necolas/postcss-bem-linter/pull/8)

**Comment by ai** [comment]
Autoprefixer API is:

```js
postcss.use(autoprefixer) // default options
postcss.use(autoprefixer({ browsers: [] }) // with options
```

This works because plugin can be a function or a object with `postcss` property with a function.

**Comment by MoOx** [comment]
To me, a plugin should be a function.
I understand that some plugins do not need options, but we never know... All plugins are subject to end up accepting parameters (eg: postcss-calc...)

Rework ecosystem had the exact same issue.

One cool thing is that postcss can accept another postcss instance (cool to use for example cssnext as a plugin).

Other cases looks like bad design to me.
So imo, I think we should only encourage function or postcss instance.

**Comment by ai** [comment]
@MoOx 

```js
postcss().use( require('autoprefixer-core')() )
```

This empty `()` looks like weired for me. Why we can’t use `autoprefixer` without params and `autoprefixer( opts )` with a params?

**Comment by MoOx** [comment]
Consistancy for new players

```js
postcss()
  .use(a)
  .use(b())
  .use(c.postcss)
  .use(d.processor)
  //... This is kind of boring isn't it ?
```

**Comment by MoOx** [comment]
```js
postcss()
  .use(a())
  .use(b())
  .use(c())
  .use(d())
  // this looks nice :)
```

**Comment by ai** [comment]
I suggest same consistancy:

```js
postcss()
  .use(a)
  .use(b)
  .use(c)
  .use(d)
```

;)

**Comment by pascalduez** [comment]
```js
postcss()
  .use(a())
  .use(b())
  .use(c())
  .use(d())
  // this looks nice :)
``` 
Seems a good obvious way, and has the advantage to be similar to Streams pipelines.

**Comment by MoOx** [comment]
How do you provide options here ?

With that way to do, you can easily.
```
postcss()
  .use(noOptions())
  .use(whatever({a: b}))
  .use(blablah({path: "/..."}))
  .use(bestPlugin({option: "ever"}))
```

**Comment by ai** [comment]
Why

```js
postcss()
  .use(noOptions)
  .use(whatever({a: b}))
  .use(blablah({path: "/..."}))
  .use(bestPlugin({option: "ever"}))
```

is bad?

**Comment by ai** [comment]
Don’t forget that in most casses it will be like:

```js
postcss()
  .use(require('noOptions'))
  .use(require('whatever')({a: b}))
  .use(require('blablah')({path: "/..."}))
  .use(require('best-plugin')({option: "ever"}))
```

**Comment by MoOx** [comment]
Exactly. This is bad because you will never know if a plugin is a function or not.
You fixed this by adding code in the use() method. I think we should provide guidelines & not allow people to do "bad" stuff.
Rework, for example, didn't allow that. We (as authors) end up by make plugins ecosystem consistant.
By providing "one unique way" to consume a plugin, you make postcss usage easier for everyone (I think so).

**Comment by MoOx** [comment]
References: https://github.com/postcss/postcss-calc/blob/master/CHANGELOG.md#200---2014-08-06

**Comment by ai** [comment]
I agree that we need one API for all pluginis.

```
plugin = function (opts) {
    return function (css) {
        // magic
    }
}
plugin.postcss = plugin();
```

Looks like nice for me, because `require('noOptions')()` makes to many brackets.

**Comment by davidtheclark** [comment]
I like your solution @ai, because it's flexible: either way, the plugin works. I wonder if the docs here https://github.com/postcss/postcss#processor could be clarified to explain the situation, maybe provide this example?

**Comment by ai** [comment]
I have a big plans aboout docs:

- `README.md` will be only for end-users with PostCSS vs Sass features, Gulp/Grunt/webpack HowTos and plugins list.
- `API.md` with classes, methods and properties.
- `Recommendations.md` with check list for good plugin.

Future recommendations from my notes (unsorted yet):

- Link to check list for good open source
- Plugin name should be like `postcss-NAME`. Exclusion only for project, that can works without PostCSS like Autoprefixer or cssnext.
- README must contains input and output examples.
- Do not create Grunt only projects. Create common plugin and then Grunt integration.
- To be fast use regexp oly after `indexOf` precheck.
- Clone nodes from exists one. Do not create nodes by hand, because they will not have `node.source` and will not have source in source map.
- Use `node.error()` to get node source position for warnings.
- API that we discuss above.

Also there will be few recommendations for end-user PostCSS apps (like grunt-postcss or autoprefixer CLI):

- Create map file if `result.map` exists.
- Always set correct `from` and `to` option.
- Hide stacktrace for PostCSS `CssSyntaxError`. 

@MoOx @yisibl @lydell what I should add else to plugin developer recommendation.

**Comment by ai** [comment]
@davidtheclark I have next open source plan:

1. Autoprefixer 5.1 release tomorrow.
2. `postcss-simple-var` and `postcss-mixins` because I need some good example in `README.md` for Sass users (@MoOx I will mention W3C var in Modularity Feature section right after example)
3. New PostCSS docs.

**Comment by MoOx** [comment]
lgtm for a fresh start :)

I just miss the point of appealing Sass users. Who cares what are they doing ? We should better write blog post how to stop using Sass these days :)

**Comment by ai** [comment]
@MoOx yeap, I mean convert Sass users to PostCSS users :). But I think we should write PostCSS docs to convince Sass users to become ex-Sass users.

**Comment by kapouer** [comment]
Right now if i receive `postcss().use(plugin).use(plugin2)` i cannot call `.parse` on it - it's not nice when you want to configure on one side, and compress multiple files in another place.

**Comment by ai** [comment]
Runner Guidelines discussion #261

**Comment by ai** [comment]
Plugin Guidelines discussion #319
