### ISSUE TITLE
Deno release issue

### ISSUE THREAD

**Issue by ai** [postcss/postcss#1508]
We still have problems with Deno build

https://github.com/postcss/postcss/runs/1673208679

**Comment by oscarotero** [comment]
Fixed (and tagged). Thanks for the warning.
FYI, any change that requires to modify the tests will fail because the test files are not converted automatically from postcss (I've the [Deno tests in separate files](https://github.com/postcss/postcss-deno/tree/master/test)).
It's something that does not change often, but when it happens, is good to know it.

**Comment by ai** [comment]
Thanks!
