### ISSUE TITLE
Using scss variables

### ISSUE THREAD

**Issue by dirad** [postcss/postcss#1532]
Hi

Im using a basic parcel config to render a scss file via postCss

I wanted to use a variable and came across something strange.

Note the following scss
```
$max_width : 1301px;

:root {
    max-width: $max_width;
    --sed: $max_width;
    invalid_prop: $max_width;
    --valid_var_prop: $max_width;
}

```
this renders as:
```
:root {
	max-width: 1301px;
	--sed: $max_width;
	invalid_prop: 1301px;
	--valid_var_prop: $max_width;
}
```

I have also required 'postcss-css-variables' in postcss.config [not sure it is relevant though]
my postcss.config.js :
```
module.exports = {
    plugins: [
        require('tailwindcss'),
        require('postcss-mixins'),
        require('autoprefixer'),
        // require('postcss-rtl')({option:value}),
        require('postcss-rtl'),
        require('postcss-css-variables'),
    ]
  };

```

Did I misunderstand something?

**Comment by ai** [comment]
> render a scss file via postCss

PostCSS can’t render SCSS.

PostCSS do nothing. It only parses CSS and generates a string back.

PostCSS plugin do all transformations. If you need to replace `$var` you need a special plugin for that. You can use `postcss-simple-vars`, but note that it doesn’t 100% equal to SCSS syntax.

I recommend avoiding `$var` syntax since it is non-standard syntax. For your case, it will be better to use CSS Custom Properties.
