### ISSUE TITLE
Not enough errors explanation

### ISSUE THREAD

**Issue by Alexufo** [postcss/postcss#1583]
I am a new to postcss and I have a difficulties to debug postcss exceptions.

For example I spent many time to understand this exception:

![2021-05-18_01-05-07](https://user-images.githubusercontent.com/1562329/118567899-4ddd2400-b77f-11eb-8d2a-12200b830de0.png)

I can get it on if I forget to set right path to mixin file in config or forgot add options like here 
`        require('postcss-mixins')({
            mixinsDir: path.join(__dirname, '/src/css/mixins/')
        }),`

The problem was I forgot to remove `(` `)` from mixin name  `@add-mixin media (840)`  to ` @add-mixin media 840` 
But exception on the screenshot is the same for all cases. I suppose it is not dev friendly or I don't understand something.

The second. Is there css validation option in postcss? I compile wrong css file (when mixin are not worked i got nested properties) but postcss doesnot show me any info about it. I suppose I can do in a mistake in setting in future and will not catch it

**Comment by ai** [comment]
> I suppose it is not dev friendly or I don't understand something.

This error was generated in `postcss-mixins` plugin. Not in `postcss` core itself. I am also maintainer of `postcss-mixins`, but in future it is better to report this kind of issues to plugins.

The problem should not be related with `(`, since you do not have them in error message.

It is hard to say what is the problem. Show me `/src/css/mixins/` files and their content. (Let’s find a reason first and then will think about error message improvements)

> The second. Is there css validation option in postcss?

PostCSS parser has a very basic CSS syntax validation. It does not know anything about accepted at-rules and property values it and could detect only missed `;` or `}`.

But plugins has own validations. For instance, `postcss-mixins` check every `@mixin`/`@add-mixin` at-rule and throw an error on unknown

**Comment by Alexufo** [comment]
Ohh! My mistake! 
After sass I have mixin's name and `(` without space. Of couse postcss will not understand coz this mixin is really  absent. 
So I removed `(` and I got space divided name and parameter. 
`@add-mixin media(840)` - will not work
`@add-mixin media (840)` - works 
funny visual collision.
Is it mean mixin's names allows `()`? If is so, exception was right but I don't think it is a good idea.

**Comment by ai** [comment]
> Is it means mixin's names allow ()?

It does not.

Yeap, you were right. It is a bad error message. Can you send PR to `postcss/postcss-mixins` that will check mixin name and throw an error on `(` with explicit message that user should remove it?

**Comment by ai** [comment]
OK, I did it on my own https://github.com/postcss/postcss-mixins/commit/d173702a1a9078f0ad4a88b2f4b3b372c14aa560

**Comment by ai** [comment]
Released in `postcss-mixins` 8.0
