### ISSUE TITLE
Browser compatible version with standard modules

### ISSUE THREAD

**Issue by justinfagnani** [postcss/postcss#1606]
I'm trying to load PostCSS into a browser (just for the CSS parsing, not transforms) and having a very difficult time getting the various Rollup plugins configured correctly to get polyfills for Node builtins working.

Now that every supported version of Node supports standard JS modules, could PostCSS be updated so that the parser is written and published to npm as standard modules and all Node-only built-in module imports are put in Node-only entrypoints? The core parser shouldn't need the built-in `path`, `fs`, or `url` modules.

**Comment by ai** [comment]
I do not recommend to use PostCSS in the browser, because it has a big size (around 20 KB).

I see only a few small use cases for PostCSS in the browser (like CodePen). In this case, you need to use some builder which will respect `packge.browser` https://github.com/postcss/postcss/blob/main/package.json#L128-L135

PostCSS is ready that `require('fs')` will return empty object and can work without these dependencies.

**Comment by ai** [comment]
We do not plan to create a special ESM version of PostCSS without Node.js dependencies. It is better to use something like https://stylis.js.org/ for the browser (but it can’t parse complex cases).

**Comment by justinfagnani** [comment]
Some use cases are indeed like CodePen. It'd be nice to be able to make that decision on an app-by-app basis.

**Comment by ai** [comment]
We can add docs about creating browser build of PostCSS.

But, to be honest, PostCSS work in `webpack` 4/5 out of the box. You may need to configure Rollup a little to work with PostCSS. But I am not sure, that we need to add Rollup-specific docs.
