### ISSUE TITLE
Aliasing an existing variable names

### ISSUE THREAD

**Issue by krishna63** [postcss/postcss#1613]
Hi Team,

I have few `variables` which are exposed to the outside world, so that users can overwrite them as per their requirement.

Let say the default font-size for my react button component is `12px` and if used need to overwrite it then he can pass the value to the exposed variable name as shown below

```css
_variables.pcss
$old-global-font-size: 12px !default;

button.pcss
.primary {
font-size: $old-global-font-size;
}
```
Les assume a consumer(named 'A') who are consuming my button component and want to override `font-size` so they have overwritten required value as shown below

```pcss
$old-global-font-size: 14px;
```
We have configured in such a way that user configured styles take precedence over the default ones. **Now for some reason i need to rename the variable name from `$old-global-font-size` to `$new-global-font-size`.** 

```css
.variables.pcss
$new-global-font-size: 12px !default;
```

But i cannot ask the person A to change the variable name in his code because the list is really huge and he is not interested to do that as well in his code base,

So in my code do i have any way to alias the new variable with the old one or should we need to write a new plugin for achieving the desired feature ?

Please suggest.

**Comment by ai** [comment]
Am I right, that you are using Sass variables right now, because `postcss-simple-vars` doesn't support `!default`?

Short answer: there is no out-of-the-box solution, but you can do almost anything if you will write custom plugin.

You can write a custom plugin, which will change Sass code (via `postcss-scss` syntax) and add something like `$old-global-font-size = $new-global-font-size`.

See Writing Plugin docs in this repo.

If you want to migrate from Sass to pure PostCSS solution, you can fork `postcss-simple-vars` and add `!default` and alias feature. It is very simple. It is just one file plugin.

**Comment by krishna63** [comment]
@ai : Thanks for the quick reply. Request to clarify on below things ?
Consumers generally pass me a file which holds the variable names and there preferred values. 

And i would like to **remove the reference of the renamed variables form my `varibales.pcss` file**, so while assigning the value can is there any way to check if the deprecated variable is configured in that file ? if yes then just take that value and assign it the respective CSS property. That way i will have a backward compatibility

Could you confirm me on two things ?
1 Is my approach to the problem is correct ?
2. should i write a postcss plugin or sass mixin ?

**Comment by ai** [comment]
You can do anything with source code in PostCSS plugin. Including this plan.

Sass mixin can't change variables and can't be helpful here.
