### ISSUE TITLE
Mixin plugins

### ISSUE THREAD

**Issue by ai** [postcss/postcss#162]
What mixin plugins we should add for PostCSS?

Sass like syntax (will be very important for ex-Sass users):

```css
@mixin clearfix {
  &:after {
    content: "";
    clear: both;
  }
}

@mixin border(width) {
  border: width solid black;
}

.box {
  @include clearfix;
  @include border(2px);
  width: 500px
}
```

Stylus (better CSS syntax support, but you didn’t know where you have mixin and where you have some new property):

```css
.box {
    clearfix: 1;
    border: 2px;
}
```

/cc @yisibl @MoOx @morishitter

**Comment by ai** [comment]
Also we need extend plugin for ex-Sass users. I think about this API:

```css
%placeholder { }
.a { }

.b {
  extend: %placeholder, a;
}
```

**Comment by ai** [comment]
Maybe somebody know some CSS 4 draft for this case?

**Comment by yisibl** [comment]
`clearfix: 1` ?

```css
@placeholder a { }
#b { }
.foo {
  extend:  a, #b;
}
```

More: https://gist.github.com/yisibl/7bc319a39c85d32b7486

http://dev.w3.org/csswg/css-extensions/

**Comment by hax** [comment]
@yisibl I don't find the syntax for placeholder in css extension draft, but your example seems ok. But mixin is too powerful and complex, up to now I have no idea how it can be introduce to css extension spec...

**Comment by yisibl** [comment]
[DRY-ing Out Your Sass Mixins](https://github.com/at-import/toolkit#dry-mixins)

**Comment by ai** [comment]
Maybe we should use this notation for PostCSS plugins to split noraml CSS properties and mixins:

```css
.foo {
    +triangle: top 10px red;
}
```

**Comment by yisibl** [comment]
`+` is IE  hack.

**Comment by yisibl** [comment]
[Sass Mixins to Kickstart Your Project](http://www.sitepoint.com/sass-mixins-kickstart-project/)

Vendor Prefix Mixin

```scss
.element {
  @include prefix((transform: translate(-50%, -50%)), webkit ms);
}
 
.other-element {
  @include prefix((
    column-count: 3,
    column-gap: 1em,
    column-rule: 1px solid silver,
    column-width: 20em
  )), webkit moz);
}
```

output

```css
.element {
  -webkit-transform: translate(-50%, -50%);
  -ms-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
}
 
.other-element {
  -webkit-column-count: 3;
  -moz-column-count: 3;
  column-count: 3;
  -webkit-column-gap: 1em;
  -moz-column-gap: 1em;
  column-gap: 1em;
  -webkit-column-rule: 1px solid silver;
  -moz-column-rule: 1px solid silver;
  column-rule: 1px solid silver;
  -webkit-column-width: 20em;
  -moz-column-width: 20em;
  column-width: 20em;
}
```

**Comment by morishitter** [comment]
I agree if implemented as a plugin, be not in core. But, is this postprocessor? I think, the input of postprocessor is just CSS code browsers can interpret.

**Comment by ai** [comment]
@morishitter for example CSS custom properties uses CSS, that current browsers can not interpret. I think we should not think only about standard CSS, because we must to find some new ideas.

**Comment by morishitter** [comment]
CSS custom properties plugin, postcss-custom-properties is polyfil of CSS4. 

> we should not think only about standard CSS, because we must to find some new ideas.

I think so too :) But, this is not out of scope of PostCSS.

**Comment by princed** [comment]
+1 for SCSS-compatible syntax mixin-plugin. 
This would definitely make easier switch for SCSS users.

**Comment by lydell** [comment]
I’m not opposed to this kind of plugins—I think they’re cool :)—but why re-create Sass features instead of just using (a subset of) Sass itself? (Just curious.)

**Comment by ai** [comment]
@princed yeap, Sass migration is a main reason for this plugin for me.

@MoOx @morishitter @yisibl but also there is a very common user case when we need mixins:

```css
.icon.is-twitter {
  color: #0000aa;
}
.icon.is-twitter:hover {
  color: #0000ff;
}
.icon.is-youtube {
  color: #aa0000;
}
.icon.is-youtube {
  color: #ff0000;
}
…
```

Sometimes we have this long repeations with small changes. For example, different color for social networks or different color for graph column type. We should have some tool to clean this code.

I think some custom application mixin for this cases is wrong way, because if we move network colors to this JS plugin, we hide style code from CSS file.

But maybe we can find some new better way to it? `@each`?

```css
@each (twitter #0000aaa) (youtube #aa0000) {
    .icon.is-$1 {
        color: $2;
    }
    .icon.is-$1 {
        color: darken($2, 0.1);
    }
}
```

This is a just a idea (with `$1` syntax we will not be able to put `@each` inside other `@each`)

**Comment by ai** [comment]
@lydell the most funny thing is that in PostCSS 4.0 we can implement most of Sass features (only `//` comments requires Custom Parsers) :D.

But Turing machine implementing is really hard (also it is a good rule to store logic in JS and presentations in CSS).

**Comment by princed** [comment]
@lydell Mixins and nested rules are only things we're using from SCSS, so it looks very tempting to replace big thing (written in Ruby or C/C++) with couple of postcss plugins (which we're using as well for autoprefixer and csswring).

**Comment by ai** [comment]
@princed also I want to create shorter syntax for variables https://github.com/postcss/postcss/issues/95

**Comment by princed** [comment]
Can't wait for it :)

**Comment by ai** [comment]
@princed BTW, do you know, that nested rules are already supported? [postcss-nested](https://github.com/postcss/postcss-nested)

**Comment by morishitter** [comment]
Certainly, mixin and nested rules that Sass has are very useful, because we can write code more shortly. I'm not opposed to these plugins.

PostCSS was able to build not only postprocessors but also preprocessors (meta language), hehe :D

**Comment by MoOx** [comment]
@ai your example with `@each` should be done with a simple templating system.

PostCSS should stick to a "valid" css syntax (eg: do not get specific code in it's core for something like `@include`).

If postcss can parse that

```css
@mixin stuff (/*...*/) { /* this line should be ok? */
  /*...*/
}

selector {
  +stuff: a b c; /* sass like @include */
}
```

it should be enough for you to continue outside postcss core :)

For nesting, postcss will eventually need to parse w3c draft about that http://tabatkins.github.io/specs/css-nesting/

**Comment by ai** [comment]
@MoOx when PostCSS will be able to use Custom Parsers we can create special parser for with *non-w3c* draft ;)

**Comment by kadmil** [comment]
Personally, I like "good old" sass-less mixin syntax. Looking on Stylus option and wonder, how much time will be lost in debug mode with "mixin-as-class-selector" thing.

**Comment by MoOx** [comment]
We should totally not encourage this kind of usage of postcss.

Sass has for now 2 implementations, with one is pretty fast. We should not encourage new postcss users to do sass like stuff. It's just a matter of habits.
Switching to postcss to do write Sass code again looks really stupid to me.
Chaining sass with postcss is not a big deal for performance (if you use libsass).

By writing modular components, I surprised myself to never need any mixin (and I write quite a lot of CSS).
And if I need to generate some code, I'll use some simple templating depending on the programming language I can use on my backend/dev env.

What most users need is a good & coherent methodology, not just mixins & placeholder.
This should totally not encouraged.

That being said, if postcss do not add non CSS stuff in it's core, I don't care what community does with it ^^.

I think we should just teach people how to write modular code instead of giving them tools to write messy stuff.

**Comment by ai** [comment]
@MoOx how you suggest to solve mu case with many icons with different colors for each networks?

**Comment by ai** [comment]
@MoOx of course PostCSS core will be only parsers, not mixins :). I open issue in this repo only because plugin repo name is depend on mixin syntax we will choise.

I agree that mixin solution maybee not the best one. But anyway we need some solution for repeating blocks. Maybe some very different that mixins. So let’s collect ideas and unofficial specs :).

**Comment by ai** [comment]
@kadmil @princed can you show some examples where you will need mixins. It will helps us to find best way.

**Comment by kadmil** [comment]
I've tried some classless css stuff; without use of classes, only knowing what markup will be, it was quite convenient to have mixins for "padding: 10px; border: solid 1px red;" things. Or flexbox
```
@mixin flexbox-container {
    display: flex;
    flex-wrap: wrap;
}
```

**Comment by MoOx** [comment]
Seriously, using a `each` loop for 4/6/8/10 colors looks like overkill to me.

```
.icon.is-twitter {color: #0000aa}
.icon.is-twitter:hover {color: #0000ff}

.icon.is-youtube {color: #aa0000}
.icon.is-youtube:hover {color: #ff0000}
```
This code is simple, easy enough to work on. Noob can interact. It's native. No need for anything else to understand/debug.

**Note: I don't hesitate to write single line block when I get only one property involved**

For placeholder/extend, I just use `class=""`.

CSS is not a programming language. It's a language used **to describe**. Reading it should be easy.

**Comment by kadmil** [comment]
I'm just regular not-so-fond-of-css guy, so maybe it's just lack of education, like @MoOx assumed. BTW, if there's a way to modularize css without classes (there could be so many of them, of my!) and mixins, point me to it, please.

**Comment by MoOx** [comment]
Here is another maybe more maintainable snippet that is easy to read.

```css
:root {
  --color-twitter:  #0000aa
  --color-youtube:  #aa0000
}
.icon.is-twitter {color: var(--color-twitter)}
.icon.is-twitter:hover {color: color(var(--color-twitter) b(+10%))}

.icon.is-youtube {color: #aa0000}
.icon.is-youtube:hover {color: color(#0000aa b(+10%))}
```

**Comment by MoOx** [comment]
Oups.

**Comment by kadmil** [comment]
@MoOx yep, this case seems solvable with variables. But what about my flexbox example? To be more specific, there was some custom flexbox-connected stuff in couple of elements besides mixin properties. Mixin looked quite handy.

**Comment by kadmil** [comment]
@MoOx one more thing, I can't really see any readability issues with mixins besides good naming, which is a more general problem.

**Comment by princed** [comment]
@ai To replace existing scss mixin, i.e. with partials with 0 to 3 params to insert.
Like:
```scss
@mixin btn-box-shadow($opacity) {
  box-shadow: inset 0 1px rgba(255, 255, 255, .4), inset 0 0 0 1px rgba(255, 255, 255, $opacity);
}
```

**Comment by ai** [comment]
@MoOx we supports 12 social networks and this template needs normal, `hover` and `active` states. What will be if designer ask to change `b(+10%)` to `b(+15%)`? This is a main DRY case in programming.

**Comment by ai** [comment]
I see 3 cases for Sass mixins:

1. Hide CSS hacks like `clearfix`. In PostCSS we should do it with JS plugins. maybe we need simple API like `rework-mixin`.
2. Create a DSL for current design language like `pressable` or `hover-color-transform`. In PostCSS we should do this in app’s custom JS plugins too.
3. DRY in CSS like in that my icons example above. We can’t move it to JS plugin because we will decrease readility.

**Comment by MoOx** [comment]
case 1 don't need a mixin syntax. postcss plugins can do that already ([clearfix example](https://github.com/cssdream/cssgrace/blob/73bc47c62a00165e1df0e6a1ef0828ebd1d0426a/lib/index.js#L200-L257)).

**Comment by ai** [comment]
@MoOx yeap, I wrote it. We should use JS plugins for 1 and 2 cases.

**Comment by MoOx** [comment]
for case 3, nesting will probably be enough most of the time :p

**Comment by ai** [comment]
@MoOx what nesting you suggest? Can you show a some pseudocode example?

**Comment by MoOx** [comment]
When custom props will work everywhere (or if you write a client side polyfill, not a "simple" transformation), you will be able to write this

```css
.is-twitter {--color: blue}
.is-youtube {--color: red}

.is-twitter,
.is-youtube {
  color: var(--color);
  {
    &:hover {color: color(var(--color) b(+10%))}
    &:active {color: color(var(--color) w(+10%))}
  }
}
```

But for now I prefer to stick with a few repetitive lines, it's never a big deal to edit in vim (even for 10*3 lines) ;)

**Comment by davidtheclark** [comment]
I am confused by this thread. Is a mixin plugin *going* to happen and this is to determine what syntax to use? That's the conversation I'd like to contribute to.

I agree with @MoOx that using a standardized syntax is always preferable (because it's interoperable and future-proof) *if there is one*; but I disagree that PostCSS needs to limit itself to CSS standards. Is additional flexibility (e.g. for at-rules declaring or including mixins) a significant issue? I'm not clear on @ai's stance on that.

And as @ai pointed out: if PostCSS wants to win over developers who have become accustomed to the powers or Sass and Less, that's not going to happen by dismissing features that people do find valuable in real experience. For every person that thinks "programming" features of Sass/Less *spoil* CSS and *hurt* maintainability, there's another *with just as much experience* who believes the opposite, that those features *improve* CSS and *help* maintainability. It's silly to even debate whether there are "actually" any "legitimate" use-cases for mixins.

**Comment by davidtheclark** [comment]
Also: some of the comments above (and elsewhere) suggest just using both --- (maybe a subset of) Sass for Sass-y stuff, PostCSS for legit CSS. That's generally fine, sure; but here are two reasons I'd prefer to *replace* Sass:

- You can only *manually* enforce restrictions on Sass features. Whereas with PostCSS you can pick and choose the features you want enabled --- actually limit possibilities.
- I want to simplify my stack. Eliminating Ruby would be nice. Then I could use Libsass (though I'd hope that PostCSS plugins would be more stable and clearly documented), or I could stick with pure JS and use Less; but especially in an enterprise stack the fewer dependencies the better.

Still, maybe I'll end up using Less for mixins and PostCSS for future-friendly CSS, if that's what it comes down to.

**Comment by MoOx** [comment]
Note: We should not care about "win" over developers. We should not add things "just" to appeal.
When I develop something I care about myself first. That's how to make good project.

Btw "find valuable in real experience" is just a matter of habits :p

But I get your point. Anyway it will be done outside postcss core since postcss will support custom parsers from what @ai said. So not sure this should be discussed here anymore :)

**Comment by benfrain** [comment]
Great thread. It seems the debate is primarily a philosophical one. @MoOx is arguing purist values (should only future proof specced CSS) while others see the benefit in the utility of tools that LESS/Sass/Stylus have brought to style sheet authors.
I think it would be a mistake to be too prescriptive. I mentioned to @MoOx this: https://github.com/cssnext/cssnext/issues/60 which he dismissed as unlikely and something that could be easily solved with some other templating solution, yet this was not a fabricated scenario, it was an actual problem, as a style sheet author (yes, over 100 variants on a site that has millions of daily users) that Sass could solve and PostCSS/cssnext could not.
The ability to plugin extras (e.g. requiring 'post-css-data-structures') if the user required it seems like the best of all worlds. Using PostCSS raw gives you @MoOx pure form, @davidtheclark can keep his build clear of things he doesn't want and any user like myself, that would embrace extra tools such as these could do so.

**Comment by ai** [comment]
@davidtheclark this thread is only about mixin syntax :) philosophical comments re offtopic :D.

What syntax you prefer? For what task you uses mixin right now?

**Comment by ai** [comment]
@davidtheclark @benfrain don’t worry, we definitely will have some tool like mixins to solve problems.

But we need to find best syntax :).

**Comment by davidtheclark** [comment]
Just to clarify points that may have been already clear to others... I see a few different tradeoffs, in the definition and the invocation.

## Definition

Where to define the rule-to-be-mixed-in? Inside stylesheets or outside stylesheets, in JS? Seems to me that a significant advantage of keeping the definitions in JS is that all the programming you might want to do to make that mixin flexible (which may include conditionals, loops, calculations, etc.) would be more than possible in JS. But as long as the mixins are simple and don't need logic (which most probably are), a stylesheet definition should also work fine. I guess it would be nice if the plugin supported both?

I would be happy to use JS for mixins -- maybe it's a function that accepts the mixin's arguments and returns an object corresponding to property declarations? I'd hope that's not too much barrier for entry for people who hopefully at least use jQuery :)

One problem I can think of with definitions in stylesheets: If I defined a mixin in one file and used it in another, would the parser know how to handle this as long as a I concatenate the files in the right order, or use https://github.com/postcss/postcss-import?

A problem I can think of with definitions in JS: What about custom properties that are defined in the CSS --- would you have access to those?

Syntax for stylesheet definition ... Here are some ideas:

- New mixin at-rule, just like Sass
- New selector before mixin name, like Sass `%` placeholders

Either one seems to close enough to to real CSS syntax.

## Invocation

Two possibilities I like:

- New include at-rule, just like Sass
- A mixin property, whose value(s) would be the mixin functions, e.g.
```css
.foo {
  mixin: triangle(right);
}
.bar {
  mixin: clearfix();
}
.baz {
  mixin: triangle(up), whizbang(true);
}
```

I don't really like the precedent in the clearfix example mentioned above (`clear: fix`) because I think that obfuscates what's going on. It's too implicit. A new dev looking at the code would be justified in thinking that `fix` is a legitimate value for `clear`, and would have no reason to know (unless told) that that particular declaration is actually adding *several* declarations to the compiled CSS. I prefer the explicitness of a `mixin` property.

Using a `mixin` property means you don't have to bring at-rules inside blocks, which I don't think happens in standard CSS (is that right?). And function syntax is just like standard css functions.


Those are my ideas right. What do you think?

**Comment by ai** [comment]
@davidtheclark I agree that you need to write JS mixin if you want flexibility. But we also has many simple cases wwhen you want to have mixin in CSS. Like my icon example above.

`mixin` property looks great. There is only one problem, what if I want to put mixin, then some mu properties and then other mixin? 2 `mixin` properties looks like wierd, because in CSS properties replace prev property wiith same name. But I can’t find a good example, when I will need mixin-prop-mixin.

**Comment by ai** [comment]
Also I think maybe we need some `postcss-hacks` plugin to store all `clearfix`, `triangle`, `sticky-footer`?

```css
a {
    hack: clearfix
}
```

**Comment by ai** [comment]
@davidtheclark if you will use `postcss-import` before `postcss-mixin`, mixin plugin will know about all imported mixins.

**Comment by davidtheclark** [comment]
I'm not sure if "hacks" *need* to be distinguished from non-hack "mixins"; and I imagine there will be a lot of confusing gray areas if you really try to enforce a distinction. If you and others like the "hack" distinction, maybe that could be provided as an alternative identifier for the "mixin" property?

Interesting thought on repeating the mixin property. Repeating properties would normally result in overwriting, so you're right that it wouldn't make sense to see two mixin declarations within a rule set. While I also can't think of specific examples where this would be necessary, I wouldn't want to presume that I know all possible cases and therefore this shouldn't be allowed for ...

We could go with an in-block at-rule, like Sass. But if this is really an edge case it would be a shame to choose syntax just for rare (or maybe outright unnecessary) situation.

Really, maybe it's never necessary?

**Comment by ai** [comment]
@davidtheclark I mean to have some packs of standard hacks :). But it would be very semantic if e will have separated property for them.

**Comment by davidtheclark** [comment]
I see ... makes sense to me. :)

**Comment by davidtheclark** [comment]
Maybe we can logically prove that you would never need two mixin properties ...

AFAIK The *only* reason to care about the place you declare the mixin is if you plan to override some value that the mixin sets. So the only reason you would want mixin to come after another is if you want the second mixin to override a value that the first one sets. Ok, weird as that sounds you could theoretically handle that by placing it later in the list of `mixin:` values (e.g. `mixin: first(), second-overriding-first();`). Following that, the only reason you want want mixin1 followed by arbitrary properties followed by mixin2 is if you want to set arbitrary properties overriding mixin1 and then override those with mixin2 ---- but that's absurd. So maybe there really is no reason to worry about that. What do you think?

I thought of another possibility, too. @ai suggest above a `+` prefix to non-standard properties, and @yisibl pointed that `+` is used for IE hacks. So what about hijacking the option built in for vendor prefixes and using `-` or `_`, which are "guaranteed never to be used in a property or keyword by any current or future level of CSS"? (http://www.w3.org/TR/CSS2/syndata.html#vendor-keywords) (You could even put a prefix of your choosing on the front.) That could either work with a `mixin` property *or* each mixin you define could its own custom property, e.g.

```css
_triangle: 10px 20px red;
-triangle: 10px 20px red;
-post-triangle: 10px 20px red;
```

(This would also solve the potential problem of not being able to duplicate `mixin` properties --- just put each mixin wherever you want it.)

Then what would happen if there were no arguments for the mixin --- just no value?

```css
.foo {
  _clearfix;
  background: pink;
  color: orange;
}
```

**Comment by MoOx** [comment]
What about this

```
@mixin name(arg: default, arg2: default2) { /* or -mixin-name() directly*/
  thing: -mixin-var(arg)
  stuff: one two, -mixin-var(arg2);
  { /* tabatkins nesting proposal, this will be fun to implement :/ */
    & {
       /*... */
    }
}

.usage {
  -mixin-name: arg1, arg2;
  -mixin-name: auto; /* no arg */
}
```

About parsing order and stuff, you will need to do 2 pass like for custom props: 1 to read all mixins, one to execute all mixin replacement (to follow the CSS spirit: we can override stuff due to the cascade).

Note about the -mixin-* (mixin usage) & -mixin-var: there will never be at the same place (one as prop name, the other as value) so it should not be a big deal to handle that.

This might look verbose, but at least it can be clear :)

**Comment by yisibl** [comment]
Prefix has brought us a lot of trouble.
I think if you must add a namespace to distinguish, can consider this way:

```css
@custom-property clear {
  value: fix;
}
```

http://dev.w3.org/csswg/css-extensions/?c=M%3BO%3DD#custom-property

**Comment by MoOx** [comment]
I don't think we should use anything related to css spec if it's not to make a transpiler (like we are doing for some modules)

**Comment by davidtheclark** [comment]
@MoOx --- nice --- and you hit on the key point that if the mixin declaration is in the stylesheet its arguments have their own syntax, too.

@yisibl I wonder what you mean by "prefix has brought us lots of trouble"? A `-` or `_` prefix is guaranteed in the spec not to clash with anything in the language; and vendor prefixes work for you, right? I guess I don't understand what kind of trouble a `-` or `_` prefix could bring.

**Comment by ai** [comment]
OK. I think this syntax is nice:

```css
@mixin clearfix {
    &:after {
        clear: both;
    }
}

.icon {
    mixin: clearfix()
}
```

But I have more difficult question. What about variables? ;)

Problems:

1. We now have `var(name)` from spec, but I want to have choice and want to make `postcss-simple-vars` with Sass syntax.
2. Will be very good if we can use variables in selectors like in my icons example above.

**Comment by ai** [comment]
If we will allow to use only 10 arguments, we can use `$n` arguments like:

```css
@mixin icon {
    .icon.is-$1 {
        color: $2;
        &:hover {
            color: color($2 +l(10%));
        }
        &:active {
            color: color($2 +l(10%));
        }
    }
}

mixin: icon(twitter #0000ff);
mixin: icon(youtube #ff0000);
```

**Comment by davidtheclark** [comment]
Using `$` for `@mixin` arguments makes sense to me, @ai --- distinguishing them from the standard `var()` syntax. I'm indifferent between that and the `-mixin-var` suggestion @MoOx had above. One is familiar to Sass users; the other looks more like real CSS.

It strikes me as pretty weird, though, to put a `mixin:` declaration outside of a rule set, as in the example. I wonder if in that situation another at-rule would fit in better?

```css
@include icon(twitter #0000ff);
```

(... only using the word "include" because that's familiar from Sass ...)

Also, if so much of this is meant to match the power of Sass, it's worth arguing that giving up named parameters is a significant loss of power compared to Sass mixins. The simple `$n` is nice as shorthand; but it would also be nice to specify names sometimes?

**Comment by yisibl** [comment]
http://www.slideshare.net/stubbornella/css-wish-list
http://tabatkins.github.io/specs/css-extend-rule/ (@tabatkins )

**Comment by MoOx** [comment]
mixin & extend/placeholder are different things.
We should wait a little before doing anything, it's not even an unofficial css draft.
@ai if you go with the last syntax you offer, I will just ask for one think: handle nesting with current draft specs, instead of the simple nesting. Everything will win something in this case :)
You will need to be careful with your simple vars plugin to not handle the $var in the mixin (since it's need to be done during mixin processing)

**Comment by ai** [comment]
@MoOx you can write own parser with @tabatkins nested (it is not even a draft of spec) when PostCSS will have custom parsers.

Right now Sass nested is easier to implement (just remove states in parser). @tabatkins nested is harder to write and harder to parse without any benefits. So I don’t see a any advantages (I understand that you think that is some kind of spec, but it is not).

**Comment by ai** [comment]
@davidtheclark Really some of mixins could be written on root level. So I think `@include name` is better, that `mixin: name`.

**Comment by ai** [comment]
Also there is a third question. We will have 2 plugins:

* simple templates like `@mixin` and `@include`.
* some shortcut to create JS plugins like [rework-mixins](https://github.com/reworkcss/rework-mixins).

What names we should use for them? `postcss-template` and `postcss-mixins`? `postcss-simple-mixins` and `postcss-js-mixins`?

**Comment by davidtheclark** [comment]
Some questions:

- Maybe a silly suggestion -- but what about a *third* plugin that is *just for cloning* (no arguments, e.g. clearfix or accessible hiding)? Seems like it could be significantly simpler than the others. Maybe `postcss-macro` or `postcss-clone`?
- Would the JS mixins be `@include`d, same way as the stylesheet-defined `@mixin` mixins?

`postcss-js-mixins` is certainly clear. I'd be in favor of using `postcss-mixins` for stylesheet-defined mixins and `postcss-js-mixins` for JS defined ones.

I was thinking that  `postcss-template` is too broad, because that might suggest more logic than is there (conditionals, loops, etc.) --- but then I thought about mustache, logic-less templates ----- which is, by the way, another well-known syntax we could consider for mixin variables: `{{ something }}` (wouldn't clash with sass simple vars @ai has planned).

**Comment by ai** [comment]
@davidtheclark I have no problem with `postcss-clone`. What API do you suggest? `@clone [selector]` with `%placeholder` supports?

We can’t parse `{{ var }}` because of `{` :).

**Comment by davidtheclark** [comment]
Sure, that API seems straightforward enough.

**Comment by davidtheclark** [comment]
Eh, I'm backing out of the clone idea. It would just be duplicated work I think. Unless others disagree.

@ai If I can do anything to help out with the mixin plugin, let me know.

**Comment by davidtheclark** [comment]
I started a simple mixin plugin, for the most rudimentary use-case, here: https://github.com/davidtheclark/postcss-simple-mixin

I would really appreciate any input any of you have. (And much thanks to @MoOx for the useful patterns established in your plugins.)

I was also thinking of making a simple extend plugin, with all the same limitations as the mixin plugin, but instead of copying declarations from a definition into a rule set it would copy selectors from a rule set back to a placeholder (like Sass extending placeholders, basically, and only that).

**Comment by lydell** [comment]
I think a really simple "extends" plugin that can _only_ extend Sass-style placeholder selectors would be cool (no complicated extend arbitrary selectors rules).

**Comment by ai** [comment]
@davidtheclark I will start `simple-var` and `mixins` plugins after Autoprefixer 5.1.

**Comment by davidtheclark** [comment]
@lydell I'll work on that next, probably this weekend.

@ai Very nice. And just wanted to let you know that working with PostCSS is awesome (this was my first effort using the API). Writing that plugin was very straightforward, because PostCSS does all the leg-work and provides a very clear API. I really liked it.

**Comment by davidtheclark** [comment]
@lydell I published that simple-extend plugin: https://github.com/davidtheclark/postcss-simple-extend

**Comment by ai** [comment]
@davidtheclark pleease send PR to PostCSS README.md with your plugins ;)

**Comment by ai** [comment]
I think `@include` is a bad at-rule name, because in PostCSS it can create name conflict with other plugins (because many plugins may want use this keyword). I think it is better to have “mixin” word in every mixin plugin at-rule.

So latest API is:

```css
@define-mixin icon $color {
    .icon-$(color) {
        color: $color
    }
}

@mixin icon blue;
@mixin icon red;
```

**Comment by ai** [comment]
First unreleased version: https://github.com/postcss/postcss-mixins

**Comment by davidtheclark** [comment]
@ai Yep, that's exactly why I decided to name my at-rules `@simple-mixin-define`, `@simple-mixin-include`, etc., for postcss-simple-mixin and -extend. Also why I decided not to use placeholders in simple-extend ---- to ensure no conflicts.

**Comment by ai** [comment]
@davidtheclark do we really need `postcss-simple-mixin` anymore? And also maybe we should rename `postcss-simple-extend` to just `postcss-extend`?

**Comment by ai** [comment]
`postcss-mixins` 0.1 was released.

**Comment by davidtheclark** [comment]
I will have more time to look at `postcss-mixin` in a little bit, and probably it would be fine to just say `simple-mixin` is incorporated by it and therefore deprecated. Just want to look into it a bit more first.

As for `postcss-extend` --- that would be neat, except that it currently is "simple" in that it does not extend real selectors, just `@simple-extend-define` abstractions (like `%` placeholder only). If someone wanted to extend real selectors also, we might have a similar situation as with mixins: the "simple" functionality is just a subset in a plugin that can also do other things.

**Comment by davidtheclark** [comment]
@ai I added a deprecation notice to `postcss-simple-mixin`.

Do you want to make `postcss-simple-extend` become `postcss-extend`? There is some justification for just having the placeholder-extension "simple" functionality instead of allowing people to extend arbitrary selectors: its the extension of arbitrary selectors that causes confusion about the output code and maintenance concerns (the reason some people say never use Sass extends). Or do you think that for `postcss-extend` you want to enable whatever Sass enables? Either way, we could use the existing code in `simple-extend` as the starting point. What do you think?

**Comment by ai** [comment]
Yeap, I think `postcss-extend` is a better name for your plugin. User will send a PR for any missed features.

But @morishitter already took `postcss-extend` plugin name for [ACSS plugin](https://github.com/morishitter/postcss-extend) :(.

**Comment by davidtheclark** [comment]
Yeah ... so I suppose unless he wants to change his name (maybe to something more ACSS-targeted), maybe `simple-extend` *is* the best way? Or we could go with the terminology used [here](http://csswizardry.com/2014/01/extending-silent-classes-in-sass/) and elsewhere: "silent classes". It could be `postcss-silent-class`. I don't know, just brainstorming --- I think "silent class" is kind of neat and descriptive, but not nearly as well known.

**Comment by ai** [comment]
@morishitter what are you thinking about plugin names? :)
