### ISSUE TITLE
Verify plugin version

### ISSUE THREAD

**Issue by ai** [postcss/postcss#163]
To fix issues like this: https://github.com/w0rm/gulp-postcss/issues/14

**Comment by hail2u** [comment]
I don't think checking version in PostCSS plugins/tools is good idea.

Plugins/Tools have already clarified what version of PostCSS required to run via package.json `dependencies`. So, tools like `gulp-postcss` should look `dependencies` field when requiring PostCSS plugins/tools. This must be their job, not PostCSS.

**Comment by ai** [comment]
@hail2u what API you suggest? Because right now `gulp-postcss` receives just a array of functions and have no idea about what AST version with plugins expect. Se bug here https://github.com/w0rm/gulp-postcss/issues/14

**Comment by hail2u** [comment]
Tools can retrieve `package.json` of installed package easily. Looking `dependencies.postcss` seems enough for me.

```javascript
var csswring = require('csswring');
var postcss = require('postcss');
var semver = require('semver');

var verPostcss = require('postcss/package.json').version;
var pkgCsswring = require('csswring/package.json');

if (!semver.satisfies(verPostcss, pkgCsswring.dependencies.postcss)) {
  // Show warnings and abort!
}

// Process if satisfy
```

**Comment by ai** [comment]
@hail2u right now gulp-postcss doesn’t know plugin name. It receives only function. What new API you suggesting to gulp-postcss?

**Comment by hail2u** [comment]
I can understand what you say, but providing version checking API is `peerDependencies` that was failed on npm. This API will fail on PostCSS too. I don't think you (or we) can provide a better solution for this type of problem.

Also I think `gulp-postcss` can get a list of installed PostCSS plugins/tools from project `package.json` using findup package. So, gulp-postcss can know PostCSS plugins/tools names that may require later.

**Comment by ai** [comment]
@hail2u I understand you, but what is a benefits to check a plugin version inside `gulp-postcss` instead of inside PostCSS itself?

Right now we have `gulp-postcss`, `grunt-postcss`, `postcss-loader` and will have `postcss-cli`. Each of this tool will require some code. Then new developers will create some `whatever-postcss` and they will miss a plugin version check and we will have user reports on conflict between plugins.

Also your way requires to make a `gulp-postcss` API more compilcated. Right now we have a simple function. But you suggest to send a npm-package name to `gulp-postcss`, then we should some how send a options.

We can’t do it, but I think I didn’t understand your well, because I didn’t see any advantages of your idea.

**Comment by hail2u** [comment]
Yes, my idea does not have any advantage for checking version. Forget about it for a moment.

If I'm not wrong, implementing this type of version checking API into PostCSS core looks like implementing a dependency management option to `require()` of Node.js. I think this should be implemented on tools (like `npm`) side not on core side.

That's the main reason why I can't agree.

**Comment by ai** [comment]
@hail2u I totally agree with you, that it  is a job for npm. But npm team [was failed](https://github.com/npm/npm/issues/5080) with `peerDependencies` and now they [think](https://github.com/npm/npm/issues/5080#issuecomment-40545825), that frameworks should check plugin versions :(.

**Comment by hail2u** [comment]
Hmm... In PostCSS universe, I think “the host” in isaacs comment is `whatever-postcss` thingy, not PostCSS framework itself.

If someone wants to call PostCSS plugins without a `whatever-postcss` thingy, (s)he can resolve dependencies via `npm`. In this situation, verifying version in PostCSS means nothing and wastes its time.

If someone wants to call PostCSS plugins with a `whatever-postcss` thingy, (s)he expects `whatever-postcss` resolves dependencies for him/her because (s)he doesn't install PostCSS directly. In this situation, verifying version in PostCSS will help `whatever-postcss` thingy very much, but this mismatches what users expect. That is why issues registers to `gulp-postcss` and `autoprefixer-core` project, not to PostCSS project, I think.

Also if PostCSS provides a public API for verifying version, it will require an extra code to `whatever-postcss` thingy or PostCSS plugins and this extra code will cause a code portability problem because it is tied to PostCSS interface. It's not bad, but not good also.

This is about an API design philosophy. Sorry for not-well-organized comment!

**Comment by ai** [comment]
@hail2u Not all users will use `whatever-postcss`. Some users will have some special cases and they will use `postcss` directly

**Comment by MoOx** [comment]
This seems like a dangerous game.
If I write a plugin simple that use one method. Let's say this method work with 1.x and with all new version and even the latest not released yet (it's possible, if you rely on a "stable" method).
Now we have another one that will stop working with the upcoming release.
Plugins will never contains enough informations if they work or not with the latest release.
You can say it works between X and Y, but you can't know when this will stop working, because you never know in advance what will be broken.

I think instead of wasting energy and time on this issue, we should really focus on offering a stable API.

**Comment by ai** [comment]
@MoOx `postcss.plugin` check will not block outdated plugins. It will only add explanation if plugin throw a error:

```js
if ( semverCheck(plugin.apiVersion) ) {
    plugin(css, this);
} else {
    try {
        plugin(css, this);
    } catch (e) {
        throw new ApiConflictError(e);
    }
}
```

I agree, that stable API is more important. But we will not have 100 % stable API. Anyway we will add new methods in future.

**Comment by ai** [comment]
Also I think that `postcss.plugin()` wrap is a flexible solution for some future changes.

**Comment by ai** [comment]
`Processor#version` is in `v4.1` branch: cb7a1d61e076445d698f74d5b5c9997953ea6070

```js
var processor = postcss();
processor.version //=> '4.1.0'
```

```js
postcss().use(function (css, processor) {
    processor.version //=> '4.1.0'
});
```

**Comment by ai** [comment]
Done 3d48436

I added warning message if plugin throwed a error and had different PostCSS version.

**Comment by MoOx** [comment]
We are going to see this message all the times, cause plugins will not always have the exact same version number. No ?

**Comment by ai** [comment]
Warning message will be:

```
postcss-size is based on PostCSS 2.1.5 but you use it with PostCSS 1.0.0. Maybe this is a source of error below.

TypeError: undefined is not a function
  at /home/ai/Dev/postcss-size/index.js:57:25
```

**Comment by ai** [comment]
@MoOx nope. Warning will be printed only if plugin throwed a error: https://github.com/postcss/postcss/commit/3d48436b003fc081bc9e0694d8add0db5d65834d#diff-f392ae0a6902c13d4338a1b8725443cdR40

**Comment by MoOx** [comment]
Ok I see you tested the major version number only. Nice.

**Comment by ai** [comment]
`majorPlugin != majorProcessor || minorPlugin < minorProcessor`
