### ISSUE TITLE
A css comment vanish if I comment out this line

### ISSUE THREAD

**Issue by frederikhors** [postcss/postcss#1678]
I created a new SvelteKit app (with command from https://kit.svelte.dev/docs#introduction-getting-started):

`npm init --yes svelte@next my-app`

Here the repo: https://github.com/frederikhors/iss-svelte-kit-tailwind-comments

I added Tailwind in this commit: https://github.com/frederikhors/iss-svelte-kit-tailwind-comments/commit/84906710c497d57c8394430a482049605c2c390f.

If you run the project with `npm run dev` (after `npm install` of course) it works (Tailwind works, there is a `bg-red-500` in `__layout.svelte`).

What doesn't work is this crazy thing:

If you build with

`rm -rf ./node_modules/.vite/ && rm -rf build && npm run build`

and open the css in `build/_app/assets/pages/__layout.svelte-[NUMBERS].css` you can search for "`I_need_this_comment`" (which is a comment in `src/app.css`) and you can find it in the final css bundle.

Now if you comment out the first line in `src/app.css` enabling `@tailwind base;` and build again with the same command the comment is lost!!!

This drove me crazy!

Can you please help me understand what is going on?

Thanks!

**Comment by ai** [comment]
PostCSS itself doesn’t change CSS. Only plugins change it.

SvelteKit is a big system, it is hard to say who removes comment. Often it happens because of CSS minifier (but I am not sure that Vite in SveltKit uses `cssnano`, very likely that is not PostCSS-based).

I am closing this issue, since it is environment question. You are welcome to re-open if you will find a minimalistic example where PostCSS parser break something itself.
