### ISSUE TITLE
How to solve postcss deprecation warning?

### ISSUE THREAD

**Issue by avmesquita** [postcss/postcss#1759]
- Generating browser application bundles...(node:18740) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at D:\..........\node_modules\postcss\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by ai** [comment]
Update PostCSS and Node.js. We fixed this issue a few months ago.

As you can see we don’t have `./` in `exports` anymore https://github.com/postcss/postcss/blob/main/package.json#L8=

Seems like you are using old version of PostCSS. Note that you will need to update nested dependencies too.

For instance, you can try `npm update` to update *all* dependencies. To update only `postcss` dependency there are many tools but I can’™ recommend the right one without knowing your environment.

**Comment by avmesquita** [comment]
I made a update (npm update postcss) but project has a set of components which cannot update.

**Comment by Ghufran496** [comment]
hey i am not able to solve this due to this shiiiity error i m not able to deploy my project. help plz (node:10708) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at H:\DeployedFYP\fyp\node_modules\next\node_modules\postcss\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
