### ISSUE TITLE
Compare PostCSS with other Frontend tool

### ISSUE THREAD

**Issue by ai** [postcss/postcss#237]
Maybe some examples from other frontend tools will helps to understand what is difference between PostCSS and Sass?

For example, we can compare PostCSS plugins with Gulp plugins. They a same small and making only one thing.

And we  can say that PostCSS is like a Babel from CSS.

@davidtheclark @MoOx what do you think?

**Comment by MoOx** [comment]
postcss itself is "just" api + parser (engine)
cssnext is babel equivalent https://twitter.com/AntJanus/status/571181130814242816

**Comment by ai** [comment]
@MoOx yeap, you are right :).

**Comment by MoOx** [comment]
You cannot compare postcss to gulp. Lot of tools have their own ecosystem.
Postcss (like rework) is just an engine that allow modular custom preprocessor (=> it's a big thing)

**Comment by MoOx** [comment]
Found one short sentence to explain what is postcss & what is solve, and you should be good.
Example: "Make your own CSS pre-processor in a flash" or "Build your modular & fast preprocessor in a minute"

**Comment by ai** [comment]
Yeap, this slogans is nice. Maybe I should use them in talk on Frontend.fi.

**Comment by iamvdo** [comment]
Maybe we need to add more examples to better understand in which cases PostCSS is better than Sass+Mixins library ?
This is what I tried when I gave a conference on CSS postprocessors last year. You can [see it in english here](https://translate.google.fr/translate?sl=fr&tl=en&js=y&prev=_t&hl=fr&ie=UTF-8&u=http%3A%2F%2Fslides.iamvdo.me%2Fblend14%2F%23%2F&edit-text=&act=url ), but be careful, code indentation is broken by Google translate. (see in french here: http://slides.iamvdo.me/blend14/)

**Comment by ai** [comment]
@iamvdo thanks for slides.

**Comment by davidtheclark** [comment]
I do agree with @MoOx that "postcss is just api" --- but I think that people reading about PostCSS ought to (and already do) think of it as a tool powering an ecosystem of plugins, and that ecosystem is the hot new thing. The term "PostCSS" is going to be used ambiguously to refer to either the engine itself or the ecosystem, and that's just inevitable because that's how people use them words :)

I don't think that most people are going to build their own prepreprocessor with PostCSS: they are going to use existing plugins. If you market PostCSS primarily as a way to "build your own plugins" that will intimidate people, and you will not get very many converts from Sass. Of course it's important that you *can* build your own plugins with PostCSS, but I think the existing plugin ecosystem also ought to be part of an effective slogan.

I think a comparison with Gulp would be appropriate, even though the two engines do very different things. People also use "Gulp" to refer to both the engine and the ecosystem. Both ecosystems are filled with plugins that are designed to "do one thing and do it well".

I might be able to offer more ideas later; have to get back to work now :)

**Comment by MoOx** [comment]
Even before PostCSS era, lots of people were using BEM to avoid classic preproc and their mixins. I think there is already lots of resources about that.

**Comment by iamvdo** [comment]
The main purpose here is "how to convert people from preprocessors to PostCSS", and I think that the actual README is a bit off track. I'll try to explain my point of view.

I've never used preprocessors. I've never felt the need of such features when writing CSS, mainly because I work on small projects. We know that best parts are variables, nesting and certainly loop and tests (note that we don't need a preprocessor to do that). The main problem with preprocessors is not preprocessors themself but mixins libraries like Compass or Bourbon. So much more people still use preprocessors only to get prefixes :/

On the other part, I've always though that postprocess is a good thing. In 2010, I wrote prefixmycss.com that adds CSS prefixes automatically. OK, it seems rather old now, but at this time, it was the first tool doing that.

When I first discovered Autoprefixer, I was like: "OK, now we can deal with prefixes in the best possible manner". So I deeped dive into PostCSS (it was in version 0.3) and tried to apply exact same principles as for prefixes. And that's the best part of PostCSS: no need for dependencies and write only CSS!

The actual README is a bit too high level imo. Examples are only based on cssnext, and can discourage people from switching from preprocessors. cssnext is a really great tool, but don't face us, it's basically a preprocessor based on future CSS syntax. As an example, people don't want to use variables the hard way, like:

```css
:root{
    --color: red;
}
.e {
    color: var(--color);
}
```
when they can use (in Sass for example):

```css
$color: red;
.e {
    color: $color;
}
```
The argument saying that it's future-proof  is irrelevant because CSS Custom Properties are not variables, so in the future we won't use CSS variables like we do it for now. The argument about speed is great, but not good enough, who cares about 50ms ?

People are not idiots, they won't switch their tools for an identical one that doesn't simplify much their workflow. That's why we can't compare PostCSS and 
preprocessors. Someone who really need advanced preprocessors features will still use preprocessors.

The better choice to me is to help people understand how they could benefit from integrating postprocessors in their workflow, not want them to use something completely new. The README should mention more simple use-case (how to switch from mixins libraries for example).

Personally, I will continue to use only PostCSS, but I understand the reason why others want to use a preprocessor. I created Pleeease in this way: simplify the connection between pre- and postprocessors. I know this is not your point of view and that's the main reason you remove Pleeease from plugins list, but you really should think about that.

**Comment by davidtheclark** [comment]
Interesting comment, @iamvdo . I'm wondering: What do you consider to be the benefits of PostCSS that should be emphasized? That wasn't clear to me from your comment.

And a side note, just something that comment got me thinking about again: I'm pretty sure that given the range of PostCSS plugins available already (and the infinitely more possible), the "preprocessor"/"postprocessor" distinction is kind of meaningless. We just have processors.

**Comment by iamvdo** [comment]
> What do you consider to be the benefits of PostCSS that should be emphasized?

For now, simplicity. You don't need to learn something new to use PostCSS, you don't have to use cutting-edge feature, it works out of the box, right on your CSS. Autoprefixer is not emphasised enough imo (an example with flexbox?). For people using preprocessors, they have to see how PostCSS will simplify their code, something from:

```css
.e {
    @include rem(font-size, 2rem);
}
```
with a mixin, to:
```css
.e {
    font-size: 2rem;
}
```
with no mixin. And it works even in edge cases like `.e { border: solid 2rem #000 }` where mixins fail.

Then, told that PostCSS is much more than that. It can provides fallbacks, extend language, improve a11y and you can even create your own processor (based on future CSS syntax if you want). The plugins list is really helpful and well classified though.

>We just have processors.

Absolutely. Pre or post, we just process our CSS. :)

**Comment by kud** [comment]
Postprocessor means it's done by the client like handlebars not compiled.

**Comment by ai** [comment]
@iamvdo hm, you suggest right ideas. But I think now we should wait for more understanding. We need to promote PostCSS widely and receive and feedback. I think we will get feedback very closer to your ideas, but real feedback is always is more import.
