### ISSUE TITLE
postcss-full-extend plugin?

### ISSUE THREAD

**Issue by davidtheclark** [postcss/postcss#321]
As opposed to postcss-*simple*-extend ...

I've received a few requests for postcss-simple-extend that basically boil down to "give it the power of Sass extends". I understand the impulse but I also think there's value in having the "simple" plugin. The "simple" code is very straightforward and fast, whereas a "full" extend would have many more requirements, inevitable complications, probably need multiple runs through the css, etc. (Also, I personally want to restrict my codebase to the functionality of *simple* extend.)

So I was thinking that maybe somebody who wanted full extends would want to create a postcss-full-extend plugin?

cf. https://github.com/davidtheclark/postcss-simple-extend/issues/6, https://github.com/davidtheclark/postcss-simple-extend/issues/3, https://github.com/davidtheclark/postcss-simple-extend/issues/2

**Comment by morishitter** [comment]
@davidtheclark 

Hi, I'm the author of [AtCSS](https://github.com/morishitter/atcss) and I made [postcss-extend](https://github.com/morishitter/postcss-extend). postcss-extend is annotations based `@extend` plugin for AtCSS.

If you will make `postcss-full-extend`, It's good for me to hand over the name :) I will rename ex, postcss-annotation-extend and unpublish postcss-extend.

**Comment by MoOx** [comment]
I am interested in that too since for cssnext since there is a unofficial draft for that http://tabatkins.github.io/specs/css-extend-rule/ (related: https://github.com/cssnext/cssnext/issues/100)

@morishitter I think you should not unpublish, but just make a major bump. That's enough. Unpublishing is bad and I am not even sure you can do that on npm now (version number that were used are still locked).

**Comment by davidtheclark** [comment]
Given the caveats about Sass `@extend` and media queries, I don't quite understand what's supposed to happen in Example 3 from that spec draft, with the `@media` query. Should `.serious-error` have `color: red; width: 100%;` or only `width: 100%`? Anybody know?

**Comment by MoOx** [comment]
Maybe @tabatkins now since he is the author of this `@extend` draft :)

**Comment by tabatkins** [comment]
`@extend`, as defined in the draft, cannot be emulated by a preprocessor. It's impossible, due to the way specificity works.  `@extend`, as Sass does it, is slightly different - specificity is different, and it has to use a number of heuristics to limit the combinations it actually generates to those most likely to be useful.

@davidtheclark As long as the `@media` query matches, any `.serious-error` elements act like they have `.error`; that implies that they get both the `width` and the `color` properties.  If the '@media` query doesn't match, then `.serious-error` elements don't act like `.error`, so they get neither.

**Comment by davidtheclark** [comment]
Thanks @tabatkins. That info paired with the details of Sass's `@extend` means I don't have the motivation myself to write this full-extend plugin and wade into all the complexities. simple-extend is all my team and I will use for now. Maybe somebody more attached to Sass's `@extend` will take it on.

**Comment by travco** [comment]
Although originally just a fork intended to extend (terrible puns) existing functionality with  @davidtheclark 's [postcss-simple-extend](https://github.com/davidtheclark/postcss-simple-extend), my repo: 

https://github.com/travco/postcss-simple-extend 

has ballooned to roughly simulate the [cssnext spec](http://tabatkins.github.io/specs/css-extend-rule/). Although it's not *really* a replacement for SASS's `@extend`, I don't think it can really be called "simple-extend" anymore. So I'm tempted to take up @morishitter 's offer.

The repo is currently in a 'all intended features' state: stable, with tests, and (passable) documentation.

**Comment by timkelty** [comment]
+1 for either making @travco's fork `postcss-extend` or something else canonical.
Seems to me as close as we can get to the spec with a preprocessor.

**Comment by morishitter** [comment]
@travco Cool! If you want to publish it as `postcss-extend`, I will rename my package to the other name.

**Comment by travco** [comment]
That would be awesome @morishitter, I appreciate the willingness.

**Comment by morishitter** [comment]
@travco I unpublished `postcss-extend` and renamed to [postcss-annotation-extend](https://github.com/morishitter/postcss-annotation-extend).  Feel free to publish your package named as `postcss-extend`:)

**Comment by travco** [comment]
@MoOx we should be able to call this issue resolved, it has been [up on NPM](https://www.npmjs.com/package/postcss-extend) thanks to @morishitter. 

I don't know if/where you want this listed under in the postcss README. Technically it's both a future syntax (should be as close to spec as possible) and a language extension. 

I'm more than happy to make a pull request making edits to the README if that's easier on your end.

**Comment by travco** [comment]
@ai this can be closed thanks for PR #454 

Thanks again :smiley:
