### ISSUE TITLE
Do not add plugins twice from plugin packs

### ISSUE THREAD

**Issue by ai** [postcss/postcss#325]
The problem:

```js
postcss([
    require('autoprefixer-core'),
    require('cssnext')
]);
```

Autoprefixer will be used twice: from first plugin and as part of cssnext plugins pack.

In PostCSS 4.1 we has `plugin.postcssPlugin` with plugin name. But we can’t remove any double plugins, because some user a want to do different actions with same plugin:

```js
postcss([
    require('stats')({ label: 'Origin sources' }),
    require('cssnext'),
    require('stats')({ label: 'Compiled CSS' }),
]);
```

I saw two possible solutions:

* Ignore already added plugin, when we will flat (see below) plugins pack
* Add special mark to plugin, that it can be run twice.

### Plugins Packs Flating

If plugin pack returns `Processor` instance, PostCSS will take its plugins directly without pack wrap:

```js
var cssnext = require('cssnext');
cssnext instanceof Processor //=> true
postcss([ cssnext ]).plugins //=> [customProperties, calc, customMedia, …]
```

@MoOx @ben-eb @morishitter What do you think?

**Comment by ben-eb** [comment]
Would it be possible for a plugin pack to get a list of plugins that have "already run" and include them based on that data? For example, if someone wants to use cssnext and cssnano together, then they both contain `postcss-calc`. But in cssnano's case, it does not need to run postcss-calc again because cssnext already performed that conversion.

I think the plugin author should be responsible for deciding if a bundled plugin should be run or not. Like you say, there are going to be cases where a *user* wants to run a plugin twice for good reason. We shouldn't prevent that from happening.

**Comment by ai** [comment]
@ben-eb I afraid many packs author will forget to add this checks. It works for PostCSS core.

**Comment by ben-eb** [comment]
I think that responsibility should lie with the plugin developer though, and not the user. Because the developer should be familiar with how a PostCSS plugin chain works, and what potential plugin collisions exist. Like double autoprefixer inclusion, for instance.

**Comment by ai** [comment]
Yeap, but most of plugins have collisions, so whitelist of non-collision plugins is better, that blacklist.

**Comment by tunnckoCore** [comment]
> I think that responsibility should lie with the plugin developer though, and not the user. 

:+1: 

:-1: for the proposed

**Comment by ai** [comment]
@tunnckoCore what exactly API you are talking about?

**Comment by tunnckoCore** [comment]
what API? im not talking about any API.
just do nothing in these cases. it's not postcss problem, it is purpose of rational developer mind and architecture.

**Comment by ai** [comment]
@tunnckoCore code is a best way to describe architecture. Buzzwords can mess us if we didn’t see real code.

**Comment by ai** [comment]
I suuggested this API:

```js
module.exports = function () {
    return postcss([ plugin1, plugin2, stats ], { ignoreDouble: ['stats'] });
};
```

**Comment by MoOx** [comment]
If you want to do something, please keep things simple, just put a warning and allow some plugins to tell postcss that they can be run multiples times. Don't do magic stuff that remove silently a plugin from the chain.

Your example with autoprefixer and cssnext is bad because autoprefixer must be called after. So we should totally warn and not just remove the 2nd call silently.

**Comment by tunnckoCore** [comment]
>  keep things simple

:+1: 

> Don't do magic stuff that remove silently

:+1: exactly

**Comment by jeffjewiss** [comment]
I think a warning makes sense because in the case of a plugin vs plugin pack you can't be confident which version of the plugin should take priority (the user's styles versus the pack's dependencies).

**Comment by ai** [comment]
Warning is not a solution, because I think main problems will be with doubles between two packs.

Like postcss-calc in cssnext and cssnano. I want to create PostCSS Lang (“Sass" plugins) and it will contains postcss-calc too :-).

**Comment by ben-eb** [comment]
I agree with @MoOx, we shouldn't silently remove plugins from the chain. But I would like to suggest this API for this feature:

```js
module.exports = postcss.plugin('postcss-lang', function (opts, processor) {
    if (!processor.has('postcss-calc')) {
        processor.use(require('postcss-calc')({}));
    }
    return processor;
});
```

This way the plugin pack developer has full access to the processor instance and can detect existing plugins in the chain.

**Comment by ai** [comment]
Yeap, @MoOx Autoprefixer order example is good point. Let's think about @ben-eb API.

**Comment by tunnckoCore** [comment]
@ben-eb looks better, but plugin developers also should care about versions. So there have a lot diffs if cssnano use one version of some plugin, and cssnext use other. For that Im against that at all, because the versions. U cant just set simple check like processor.has(name) and expect that would be enough.

**Comment by ai** [comment]
I think we can add some version control only on second iteration, only if we found real problem. "Always latest" is a good strategy, because PostCSS plugins is very small and have one feature. Outdated version promotion is bad.

**Comment by ben-eb** [comment]
Testing a processor based on its version number could be brittle. Let us think about user agent strings and how verbose they have gotten over time. I would not like to start basing checks on specific versions of processors should we end up in this kind of mess where the version ranges become meaningless. PostCSS plugins should be small and have one responsibility. If there are some differing versions of a processor, the newer version would enable that plugin to perform its responsibility better.

Wrapper plugins, on the other hand, should only encapsulate functionality that is already in the ecosystem. I know that cssnano still bundles functionality, but it is my responsibility to extract that out once I have enough free time (not long left for deadlines, now). I think it should be the developer's responsibility to ensure they are using the current versions of their dependencies, not PostCSS's responsibility to let them guard against certain versions. In any case, the default behaviour for a PostCSS pipeline should be to include all plugins. This functionality we are talking about here is for those developers who know that they can potentially speed up their wrapper plugin by disabling 'already run' processors.

**Comment by ben-eb** [comment]
Looking at including this for cssnano 2.0. Any updates?

**Comment by ai** [comment]
I think the latest idea was to make it by hands. But I think it is not so easy.

**Comment by ben-eb** [comment]
Yeah, I would have liked to do this by hand too, but I have no access to the current PostCSS instance. The API I proposed would allow for some really intuitive cross-module behaviour, and reduce duplication when people want to use cssnano in combination with some other modules. https://github.com/cssnext/cssnext/issues/156

**Comment by ai** [comment]
@ben-eb 

```js
postcss.plugin('name', function () {
    return function (css, result) {
        result.processor // PostCSS instance
    } 
});
```

**Comment by ben-eb** [comment]
@ai I return a PostCSS instance from cssnano: https://github.com/ben-eb/cssnano/blob/2.0/index.js#L35-L63 - are you suggesting to return a 'no-op' function that modifies `result.processor`?

**Comment by ai** [comment]
Just add this `plugin checker` function as first plugin to your processor instance. You can modify `result.processor.plugins`

**Comment by ai** [comment]
But maybe it is not the best way, but it works right now

**Comment by ben-eb** [comment]
@ai Perhaps I should make an interim module until we get full support within PostCSS?

**Comment by ai** [comment]
What is interim module?

**Comment by ben-eb** [comment]
Interim means a temporary period/arrangement. So I can make some module that provides an API for us to use temporarily, until such time as we add the feature to PostCSS.

**Comment by ai** [comment]
I think better to put this module into cssnano to do not create future ghost projects :).

I can add a plugins pack API on next week if you suggested good one :).

**Comment by ben-eb** [comment]
The only issue I have right now is that people can't consume cssnano like this: `postcss([ nano ])`, because it returns a processor and not a function; so either we should deprecate the invocation-less style of initializing a plugin or provide some means to allow a processor using this API.

**Comment by ben-eb** [comment]
Indeed, it actually doesn't matter that I am using the plugin API, because cssnano is not registered as a plugin in `result.processor.plugins`.

**Comment by ai** [comment]
Ouh. Let's think tomorrow :-).

**Comment by MoOx** [comment]
I think it's really important to warn users. Automation is a important thing: user don't want to think (we all know that because we don't want to, and this will prevent some later support).
So we should maybe add some metadata to `postcss.plugin()` for plugin developers (they know better than anyone if a plugin must called before or after ?

`postcss.plugin("postcss-whatever", function() {}, {runOnce: true})`

This way when registering the same plugin twice, we can (in postcss core) detect that a plugin has been added more than once & add a warning.

or the opposite `postcss.plugin("postcss-whatever", function() {}, {canRunMoreThanOnce: true})` because most plugin don't need to be used more than once (this will be a breaking change, so major postcss bump, but no need to edit ALL existing plugins - and I think only less than 10 make sense to be used more than once, so it looks like a good solution for me)

Or maybe we "just" should provide an easy way so plugin dev can do the warning themselves:

```js
function warn(plugin, result) {
    if (result.process.plugins.indexOf(plugin) !== 0)) {
        result.warn("postcss-import must be added before another plugin")
    }
    if (result.process.plugins.indexOf(plugin) !== result.process.plugins.lastIndexOf(plugin))) {
        result.warn("postcss-import should not be registered more than once")
    }
}

postcss.plugin("postcss-import", function(options) {
  const plugin = function(styles, result) {
    warn(plugin, result)

    // ...
  }
  return plugin
})

```

Hum I think in my last examples we can already be done without any change right ? (but that will require an update for ALL plugins)

**Comment by ben-eb** [comment]
@MoOx It doesn't help if people are using cssnext incorrectly;

```js
postcss([ autoprefixer(), cssnext() ]);
```

PostCSS will warn that cssnext is using autoprefixer? When in fact it is the *first* declaration that is unnecessary.

**Comment by MoOx** [comment]
You will get a warning that autoprefixer is used twice right ? So people will think like

> wait wat ? I just added cssnext, not autoprefixer... [going to think more than 2 secondes...] Ohhh MAYBE CSSNEXT IS USING AUTOPREFXIER ?!

I placed on purpose autoprefixer before anything else here http://cssnext.io/features/

**Comment by ben-eb** [comment]
I am also concerned because I plan to include Autoprefixer in a removal only mode; if people already have it set up in its default mode then I would like to just silently disable it. It doesn't make sense in this use case to warn a user that it is being loaded twice, because its usage would be for different purposes. Similarly I suggested that we have overlapping functionality that can be silently disabled. How do we handle that use case?

**Comment by MoOx** [comment]
For you use case, you should disable it by hand (since you can do that, according to the fact that result provide the processor (and so plugins list) ?)

I plan to add a warning into cssnext to warn user when they did not add cssnext in from of anything else (since it embed postcss-import that really need to be done before other stuff). This kind of plugin will be done "by hand".

Maybe the warning can be 

> You (or a plugin pack) have added 'postcss-X'  more than once, and it's not necessary: you should consider review your plugins list

**Comment by ben-eb** [comment]
OK. I'll include this hacky way for now.

**Comment by ai** [comment]
@MoOx warning is a good when people pick other plugins by hand.

But what if user take a several plugins pack and Autoprefixer is in other pack?

Maybe we should use:

1. Each plugins pack will have a code to look into `processor.plugins` and disable so plugin.
2. If it is a bad plugin pack with that code or user pick plugins by hand we will display warning.

**Comment by ai** [comment]
Maybe we need some `init` callback in `postcss.plugin()` to work plugins list. I remember that @MoOx asked about it long time ago, put I think we didn’t find a good API for it.

**Comment by MoOx** [comment]
Without an init function, that's clear that we cannot implement what you talk in your previous comment.

**Comment by ben-eb** [comment]
For what it's worth, I tried the hacky way of silently disabling plugins. It causes more problems than it solves; for now I feel that this is a documentation problem and not something we should aim to solve in code.

https://github.com/ben-eb/cssnano/issues/90#issuecomment-191994202

Now, we also have https://github.com/postcss/postcss-devtools to show a user exactly what plugins are being used by their build, and their execution time. So a user experiencing problems with duplicate plugins could load that plugin and see that indeed, Autoprefixer (or another plugin) was being loaded more than once.

It is for these reasons that I think our efforts are better spent elsewhere, so I am closing this issue.
