### ISSUE TITLE
PostCSS solution for shared components

### ISSUE THREAD

**Issue by ai** [postcss/postcss#434]
I think it is very important to be able to pack your awesome component to npm and share it with all world.

But how we can uuse power of PostCSS here?

/cc @MoOx @ben-eb @markdalgleish @jonathantneal

**Comment by MoOx** [comment]
Are you talking about some CSS only "components" like cssrecipes? https://github.com/cssrecipes

**Comment by ai** [comment]
First solution: compile your CSS on npm release.

Same case as with ES6 and Babel right now.

Problem: some users want to keep origin source code in npm package.

/cc @SavePointSam

**Comment by ai** [comment]
@MoOx nice example. I am talking about Web Components like stuff with React + CSS inside. For example, yesterday I build awesome bankcard widget and want to share it with my company. But other teams use different PostCSS plugins.

**Comment by ai** [comment]
CSS Modules looks like a best way to isolate widget. But what if other team will not use webpack. And of course, they didn’t want to install some addition plugins to their builder.

/cc @markdalgleish

**Comment by MoOx** [comment]
The problem is that for now, CSS is static. So compiling some CSS to npm provide a very limited usage.
For my css recipes, it's mentionned in the doc that it use future proof CSS. So I publish code that might works with myth, cssnext, suit-preprocessor...
It's even hard for react or others "components" to share js/html/css yet because some people (eg for React) use css modules, some other use inlines styles and some others use simple "usable" style (webpack feature).
So I don't really see how PostCSS can help or provide a solution about that. It's a global issue really not easy to solve yet. If all components were using standardised stuff (like w3c specs), but like you said, it depends on the plugins you are using...

**Comment by ai** [comment]
@MoOx yeap, I agree that it is not easy. So this issue is more about long-term discussion.

But I think current CSS do not provide good way to share components:

1. We need better isolation
2. Sometimes we need some config.
3. We need to use images from CSS, so other PostCSS plugins can be welcome in component CSS.

**Comment by MoOx** [comment]
webpack is the solution man :)

**Comment by ai** [comment]
@MoOx maybe :). But not right now, because we need some out-of-box solution. Just a few lines of code to add some awesome widget from Internet.

**Comment by MoOx** [comment]
This is not likely to happen...

**Comment by ai** [comment]
@MoOx we could have missed many science and technically inventions if we said like this everytime ;). 

Let’s plan in brainstorm. How we can solve it if we have no limitations.

**Comment by magsout** [comment]
>CSS Modules looks like a best way to isolate widget. But what if other team will not use webpack. And of course, they didn’t want to install some addition plugins to their builder.

Why didn't provide a dist version of code ? with css recipes we provide original source, but with one npm command, users that doesn't use cssnext in their workflow can launch : npm build and they can @import  css file without cssnext or anything else.

**Comment by ai** [comment]
@magsout nice start. So we can make a example how to configure `package.json` to compile `src/` to `dist/` on publish step.

What about configuration? We cen ask users to install PostCSS to configure PostCSS’s components in CSS. Somethink like:

```css
@use bootstrap;

@config bootstrap { color: red }
```

**Comment by pleunv** [comment]
Webpack might be a solution but I don't think you should force specific buildtools upon your userbase. 

I personally like browserify's transform field approach, which lets you specify a list of transforms in `package.json` that need to be performed on your code whenever you do a require() or import of that particular module. That way each module exposes everything the host project needs to know in order to correctly compile it.

In browserify it looks like this: 

```json
{
  "name": "mypkg",
  "version": "1.2.3",
  "browserify": {
    "transform": [ "brfs", "babelify" ]
  }
}
```

I dont have any hands-on experience with PostCSS (yet, currently looking at options to replace Sass and PostCSS looks very promising - assuming it can tackle all issues we currently experience with Sass :)) but in this case it could contain a list of plugins that need to be loaded whenever (a css file from) this module is imported, e.g.:

```json
{
  "name": "mypkg",
  "version": "1.2.3",
  "postcss": {
    "main": "src/styles/main.pcss",
    "plugins": [ "mixins", "nested", "simple-vars" ]
  }
}
```

This approach would be for use-cases where src files get exported for further modification/theming/recompilation in host projects, which I think happens pretty frequently.

**Comment by sevenupcan** [comment]
I've been trying to use PostCSS with web components and it's not easy. The main issue I've run into is that web components use one file to store css, html and js. The only viable way I can think of is to use a build tool to convert all your css, html and js into one file. It's not pretty or easy to work with, but only solution I can think of. Would love to see example where someone has set this up. At the moment I've only got it to work with sass.

**Comment by ai** [comment]
@sevenupcan you can use webpack and style-loader to put CSS into JS file.

But yes, it will be better to have out-of-box solution.
