### ISSUE TITLE
Clarification of some plugin guidelines

### ISSUE THREAD

**Issue by davidtheclark** [postcss/postcss#435]
I was looking over the plugin guidelines and thought of a few points that may be worth clarifying in the doc:

1. Why not write mixin libraries? Is this guideline just stating that mixin libraries are not technically postcss plugins — though they could still be shared as npm packages? The statement that "custom properties and at-rules are better ways" is left unexplained; and I think that a lot of people consider it arguable. So maybe some further explanation is needed.

2. I think readers would appreciate a sentence or two about what `postcss.plugin()` does for them.

3. "Put input and output examples" should be qualified: that applies only to plugins that transform CSS.

I was going to go in and fix up some English syntax, but I thought I may as well raise these points first.

**Comment by ai** [comment]
About mixins:

I afraid that many developers will ignore PostCSS nature and will just move their Sass mind model to PostCSS plugin. I saw few PostCSS plugins which unnecessary provide mixins for `postcss-mixins`, instead of use custom syntax, which will be much better in their task.

Other problem with mixins, is that PostCSS plugin should be independent. But mixins will require to put `postcss-mixins` above itself. What if user do not want to use mixins? What if it put `postcss-mixins` above. It is a good place to have issues.

And last but not least: PostCSS mixins are simple templates to reduce code dublication. They are not soem sort of “functions” like in Sass. Because in PostCSS philososhy we need to write code on JS, not in CSS. If developer will not change mind set and prodive old Sass way, it will put too complicated code into PostCSS mixin, it will reduce code maintable.

**Comment by ai** [comment]
About `postcss.plugin()`: I think that we should keep Guidelines short as possible, to make it absolutly clear. But I am open for suggestions :).

**Comment by ai** [comment]
About I/O examples: you are totally right. @ben-eb has same issue with Guidelines. Please send a PR with this fix.

**Comment by davidtheclark** [comment]
Thanks for responses. I'll do some quick edits before I go to work today.
