### ISSUE TITLE
postcss-stylus syntax

### ISSUE THREAD

**Issue by XOP** [postcss/postcss#602]
I'm happy with postcss-scss syntax, and it can even work with .styl files (braces, semicolons, all that sort presents) until parser meets different mixin denotion (at least). 
Are there any plans to make yet another adapter?

**Comment by TrySound** [comment]
@XOP https://github.com/postcss/postcss/issues/495

**Comment by ai** [comment]
@TrySound nope, he asked about exactly Stylus parser.

**Comment by TrySound** [comment]
@ai Does somebody want make it?

**Comment by ai** [comment]
@XOP I have no plan to write a parser for Stylus. But I wrote a good docs about writing a syntax, you can find them in this repo (sorry I am in airport, can't give a direct link). Stylus mixins and other special things, you can parse as custom at-rule with some special name.

But note, that postcss-scss is not able to compile SCSS to CSS. It just parse SCSS to PostCSS AST, but didn't execute mixins, math and other. Main purpose of this parsers is to execute PostCSS plugins directly on preprocessor source. Like linting by Styling. So it doesn't really matter, what name you will use for custom at-rules.

**Comment by ai** [comment]
@TrySound have no idea. @XOP do you want to make it?

**Comment by XOP** [comment]
@TrySound, I saw the issue (#495) and it's not related. We use Stylus without "sugar".

@ai, thanks for the answer!

I'm facing the problem of parsing, exactly, realizing compilation is another procedure :smiley:. 
But regarding mixins and sort - when postcss meets unusual token it just fails.
So yeah, adapted parser would be cool feature.

What about making it - If within our team we'll have no other options - I'll begin. So far I'm looking for the ready-to-go tools.

**Comment by corysimmons** [comment]
Why not just combine Stylus and PostCSS?

Run over Stylus first, then run over it's output with PostCSS.

**Comment by TrySound** [comment]
@corysimmons Linting for example.

**Comment by corysimmons** [comment]
What kind of stuff could PostCSS introduce that https://www.npmjs.com/package/stylint would cry about?

**Comment by TrySound** [comment]
@corysimmons Do you think somebody want to get warnings?

**Comment by corysimmons** [comment]
Why would they care if it's expected behavior? Seems like stylint is being overzealous and maybe there needs to be a config setting for ignoring `property is not valid` (or whatever other warning is being thrown). Same with other linters.

**Comment by davidtheclark** [comment]
@corysimmons The problem is that no postcss plugins can run on the code if PostCSS can't understand it. Without a stylus parser, certain aspects of stylus syntax will cause PostCSS to throw syntax errors; then the plugin won't work. 

With SCSS this kept happening as people tried to use `//` comments: that's not valid CSS, so it broke the parsing step and therefore the plugins couldn't work.

People can of course already use stylus and PostCSS together, as you say, by running stylus first. But if people want to run PostCSS plugins on *uncompiled stylus files*, then the PostCSS parser needs to not break in those files — which means we need a stylus parser.

**Comment by corysimmons** [comment]
I guess I don't understand why someone would want to run PostCSS on uncompiled CSS, then run it on Stylus? Stylus compiles down to vanilla CSS (`//` comments turn into `/* */` comments). PostCSS works on vanilla CSS.

I'm sure you guys know what you're talking about. I'm just curious what exactly messes up other than Stylint throwing warnings about invalid properties.

**Comment by XOP** [comment]
Personally, I just left the idea...
We work with SCSS now and it works fine.
I really don't have any necessity to go back to Stylus, it was a company wish :wink:

**Comment by corysimmons** [comment]
Poor Stylus...

**Comment by jmeas** [comment]
> I guess I don't understand why someone would want to run PostCSS on uncompiled CSS, then run it on Stylus?

If the situation arose that a linting error was caused by the compiler producing unexpected output, then it could be annoying to have to change your precompiled code or adjust the rules.

An analogy would be running a linter on Uglified JavaScript. I always include semicolons when I write JS, and I want my linter to enforce that. But Uglify strips them out to save on file size, so the uglified code would fail the linting rules that I want to use.

In general, I like linting what the developer inputs. I then rely on any transformation tools to correctly interpret the developer intent that when they transform it for the browser to use. But exactly what those tools output is generally not as big a concern of mine, and linting it isn't quite the same as linting developer input.

**Comment by ai** [comment]
@jmeas yeap, I agree that we need Stylus parser. But it is very complicated task. Maybe it will be better to take Stylus parser and then convert Stylus AST to PostCSS AST.

@Panya @kizu is it possible?

**Comment by alex-shamshurin** [comment]
There is a stylus parser in stylus lib. Could anyone to use it? https://github.com/stylus/stylus/blob/dev/lib/parser.js

**Comment by LestaD** [comment]
@ai has any progress here?

**Comment by TrySound** [comment]
@LestaD https://github.com/postcss/postcss/issues/602#issuecomment-149518623
I don't think somebody want to spend a time for unsupported project.

**Comment by ai** [comment]
@LestaD nope. Do you want to do it?

**Comment by LestaD** [comment]
@ai yes, I want

**Comment by ai** [comment]
@LestaD 

1. Для Stylus лучшим способом будет использовать текущий парсер. Заново создавть его будет невозможно, так как правила парсеринга очень нестабильны.
2. Изучи Stylus API, чтобы получить AST (ну что парсер отпарсил). Если нет, пинай текущих мейнтейнеров, предлагай послать PR в Stylus(там внутри точно AST есть).
3. Получив Stylus AST просто сконвертируй его в PostCSS AST. Например, как это делает postcss-sass.

**Comment by Grawl** [comment]
блин а я вообще подумываю иногда пописать на стилусе
