### ISSUE TITLE
Unknown Word: LESS Interpolated Variables

### ISSUE THREAD

**Issue by shellscape** [postcss/postcss#617]
I'm not sure if this is something that postcss intends to support or should support. I've only just started evaluating postcss, so please do forgive this if it's out of scope.

It seems that the parser doesn't understand LESS interpolated variables. Please take a look at the two examples below:

input:
```
.browser-prefix(@prop, @args) {
  -webkit-@{prop}: @args;
}
```
error:
```
CssSyntaxError: <css input>:2:13: Unknown word
```

input:
```
.browser-prefix(@prop, @args) {
  @{prop}: @args;
}
```
error:
```
CssSyntaxError: <css input>:2:3: At-rule without name
```

In both cases, regardless of the LESS-specificity of the issue title, support for both would be immensely useful for plugin processing. Please do let me know what the project's thoughts on this are.

**Comment by TrySound** [comment]
@shellscape Need less parser for such things

**Comment by shellscape** [comment]
@TrySound is that something that postcss could be extended with externally?

**Comment by TrySound** [comment]
@shellscape https://github.com/postcss/postcss-scss . Alternative for less doesn't exist, but you can change this :)

**Comment by ai** [comment]
PostCSS core contains only CSS parser (with nested rules). Less variables syntax is bad choice, because they had conflict with at-rules and as result you can't use CSS parsers to parse Less.

So it is not a PostCSS bug, because it is different syntax.

But there is way to solve it. PostCSS supports changeable custom parsers. For example, you can use PostCSS plugins for SCSS sources by postcss-scss.

So you can write custom Less parser, which will return PostCSS AST.

Here is docs how to do it: https://github.com/postcss/postcss/blob/master/docs/syntax.md

If you are too brave to start this parser, we will support you with advices in PostCSS Gitter chat.

**Comment by shellscape** [comment]
@ai amazing. I'll start looking into that. thanks much!
