### ISSUE TITLE
CSS syntax error reporting wrong line/column position

### ISSUE THREAD

**Issue by davidtheclark** [postcss/postcss#727]
@Arcanemagnus originally filed this as an issue with stylelint (https://github.com/stylelint/stylelint/issues/718):

With this CSS file:

```css
.s["] {
}
/* "" */
```

There is a CSS syntax error that reports the column of the unclosed quote on line 1 as being 18, which is far past the end of the line. It seems like it is counting all characters between the first quote and the next one as part of the line? When the comment with the `"` is removed the proper value is returned. If that comment is brought to the same line as the initial `"` the issue disappears as well.

Based on a report initially filed here: https://github.com/AtomLinter/linter-stylelint/issues/79.
![image](https://cloud.githubusercontent.com/assets/427137/12932639/88718672-cf38-11e5-87c8-94a7376ada7c.png)

This is different from #725 because the error is thrown during the tokenize step (so it's not using `node.positionBy()`).

I think that the syntax error is causing weird problems with text editor plugins, because it claims that things are happening in positions that do not exist.

Do you think there's a way to make these positions more accurate? If not, maybe text editor plugins just need to do something different when receiving CSS syntax errors from PostCSS?

**Comment by Arcanemagus** [comment]
Just to be clear, it's pretty simple to work around this bug in the editor packages by clamping the maximum character to the end of the line (Atom actually does this automatically if you feed it an invalid point, we just somewhat recently put in a warning to expose issues like this to see when a linter was feeding bad data to a helper library).

Linters are meant to _expose_ issues though, not create them, so this should be fixed at the source instead of worked around :wink:.

**Comment by ai** [comment]
Sorry, guys, I am deep into Witcher and preparation for travel. I will look iin this issue only on next week.

But PR is always welcome.

**Comment by ai** [comment]
Released in PostCSS 5.0.16.

**Comment by ildarnm** [comment]
I see the same bug in 8.4.20 version:
[https://stackblitz.com/edit/js-bxeqya](https://stackblitz.com/edit/js-bxeqya)
