### ISSUE TITLE
import style from package.json

### ISSUE THREAD

**Issue by cmnstmntmn** [postcss/postcss#783]
i'm playing with tachyons; i wish i can import it inside my project this way

`@import "~tachyons";`

since the full path to *tachyons.css* exists inside package.json. but i can't
and i have to use the full path `@import "~tachyons/css/tachyons.css";`

any ideea ?

**Comment by ai** [comment]
Ask [postcss-import](https://github.com/postcss/postcss-import) guys. `postcss` is just a core without any features. All features are in plugins. Plugin for `@import` is `postcss-import`.

Be default `postcss-import` doesn’t support `~` because `postcss-import` is polyfill for W3C spec and can’t support any unofficial extensions. But they have `resolve` callback option, when you can add `~` support.

**Comment by cmnstmntmn** [comment]
ty, i'll git it a try
