### ISSUE TITLE
Ignored syntax error in :not pseudo class

### ISSUE THREAD

**Issue by ideadapt** [postcss/postcss#872]
Hi there,

I just found, that `a:not(.a,.b)` is parsed without any errors. Following code runs without throwing an error:

```javascript
test('should throw CssSyntaxError, since only one simple selector is allowed for :not pseudo class', t => {
    let rule = new Rule({ selector: 'a:not(.a,.b)' });
});
```

According to https://www.w3.org/TR/css3-selectors/#negation only one simple selector is allowed as argument to :not.

I couldn't find a place to fix this easily. 
I expected `not` to be a token listed in tokenize.es6. But then I realized that the tokenizer is not very strict, [other tokens](https://www.w3.org/TR/css3-selectors/#lex) are also not defined there.

**Comment by ai** [comment]
PostCSS parser doesn't validate content, only syntax.

`not()` content is not a syntax.

There is a Stylelint to validate content.

**Comment by ai** [comment]
The best way to work with it is to add new rule to Stylelint to validate `not()`. You can use postcss-selector-parser to parse selector content.

**Comment by ideadapt** [comment]
In my opinion this is not about content and validation, but syntax and parsing. The parser of postcss seems not to be strictly spec conform. I think a non spec conform css input should throw an error.
As far as I see, postcss does not use postcss-selector-parser, or did I oversee something?

**Comment by ai** [comment]
We use this spec in PostCSS parser: https://www.w3.org/TR/css-syntax-3/

It is content free spec, it describe only, that functions could be in selectors, but doesn’t describe what pseudo exactly could be in pseudo.

PostCSS is content-free parser, because it could be used in polyfills or prolyffils. What if `not()` pseudo will be changed in future spec?

This is why PostCSS parser doesn’t fall on unknown property, or unknown function in value or unknown at-rule.

So there is a two way of checking CSS:

1. Tokenize CSS string
2. Create a AST by tokens
3. Check AST content

Of course `:not()` arguments could not be checked in step 1 and step 2. By PostCSS philosophy, core parser do only step 1 and step 2.

There is a Stylelint for step 3.

**Comment by ai** [comment]
Why you don’t want to add this check to Stylelint?

**Comment by ideadapt** [comment]
Hi
Thanks for the explanation.
[css3-selectors/#negation](https://www.w3.org/TR/css3-selectors/#negation) is part of [css-syntax-3](https://www.w3.org/TR/css-syntax-3). 
At [CSSLint/parser-lib](https://www.github.com/CSSLint/parser-lib) the tokenizer itself is meant to be [spec conform](https://www.w3.org/TR/css-syntax-3/#tokenization) already. Thats why I came up with this issue. parser-lib threw an error when parsing my 20k css, it revealed a useless little peace of code, something like a:not(.a,.b) :)

I still don't think validation is appropriate here, since its a tokenizer/parser issue. But however, I just learned that in CSS 4 this issue does not matter any more: https://github.com/postcss/postcss-selector-parser/issues/2#issuecomment-243084774
