### ISSUE TITLE
What about PostCSS on Ruby on Rails?

### ISSUE THREAD

**Issue by lmi11** [postcss/postcss#900]
What about PostCSS on Ruby on Rails? How I can use it?

**Comment by ai** [comment]
If you ask about PostCSS and Sprockets — there is no easy way, because your need to use `npm`.

Technically, you could install PostCSS plugins via `npm` and then use it in Sprockets.

But, nobody develop out-of-box solution. Reason is very simple — Sprockets is dead. There is no ration reasons to use Sprockets, instead of Gulp or Webpack (I was a big fan of Sprockets and I know what I am talking about). All modern techniques are only for node.js frontend build tools.

So you have 2 options:

1. Develop some solution for Sprockets. But only few teams will use it.
2. Or spent this time by moving to webpack ;).
