### ISSUE TITLE
npm install postcss Error.

### ISSUE THREAD

**Issue by hbshun** [postcss/postcss#938]
Node 5.9.1 
npm 3.7.3

------------

➜  ~ npm install postcss
npm ERR! cb() never called!

**Comment by ai** [comment]
node.js 5 is not supported anymore https://github.com/nodejs/LTS

It even doesn’t have a security updates. This is why you should update it.

This reason happens because of `caniuse-db` issue with node.js 5, but nobody will fix it, because node.js 5 should not be used in any production https://github.com/Fyrd/caniuse/issues/2981

**Comment by hbshun** [comment]
Well, thank you
