### ISSUE TITLE
Selector from AST does not match selector in stylesheet

### ISSUE THREAD

**Issue by demrks** [postcss/postcss#955]
Some selectors from the AST that needs escaping, e.g. `.class\@test`, do not match the selector in the original stylesheet, see stylelint/stylelint#2263

Stylesheet: `.class\@test`
AST: `.class\\@test`

Is this intended or a bug in PostCSS?

**Comment by ai** [comment]
A bug. But are you sure about `//` is really in strong and is not you decide tool way to show `/`. Could you check `rule.selector.length`?

**Comment by demrks** [comment]
Sorry, I'm not that familiar with PostCSS, just noticed this behaviour while using stylelint that's using PostCSS to parse the styles. You can see it in this AST explorer: https://astexplorer.net/#/M8FFZ4wVEh

**Comment by ai** [comment]
Yeap, everything correct. For example try `.class"@test" { }` it will be presented as `".class\"@test\""` (note about `\"` instead of `"`).

In JS `\` in string have a special meaning. For example `\n` is not a `\` and `n`, but it is new line. So `a\n` string could not be presented as `"a\n"`, because it mean that you have new line after `a`.

This is why `\` is escaped in JS. If you have `a\n` it will be presented as `a\\n`, this `\\` mean that it is just `\` (escaped `\`).
